const Q=[
{fi:"Narsismi on itserakkauden haava, jota peitetään suuruudella.",en:"Narcissism is a wound of self-love covered by grandiosity.",sv:"Narcissism är ett sår av egenkärlek som täcks av grandiositet.",es:"El narcisismo es una herida de amor propio cubierta por la grandiosidad.",de:"Narzissmus ist eine Wunde der Eigenliebe, die durch Grandiosität verdeckt wird.",pt:"O narcisismo é uma ferida de amor-próprio coberta pela grandiosidade.",fr:"Le narcissisme est une blessure d'amour-propre masquée par la grandiosité.",a:"Alexander Lowen"},
{fi:"Rajat eivät ole rangaistus. Ne ovat itsesuojelua.",en:"Boundaries aren't punishment. They're self-protection.",sv:"Gränser är inte straff. De är självskydd.",es:"Los límites no son un castigo. Son autoprotección.",de:"Grenzen sind keine Strafe. Sie sind Selbstschutz.",pt:"Limites não são punição. São autoproteção.",fr:"Les limites ne sont pas une punition. Elles sont de l'autoprotection.",a:"Nedra Glover Tawwab"},
{fi:"Gaslighting saa sinut epäilemään omia silmiäsi.",en:"Gaslighting makes you doubt your own eyes.",sv:"Gaslighting får dig att tvivla på dina egna ögon.",es:"El gaslighting te hace dudar de tus propios ojos.",de:"Gaslighting lässt dich an deinen eigenen Augen zweifeln.",pt:"O gaslighting faz você duvidar dos seus próprios olhos.",fr:"Le gaslighting vous fait douter de vos propres yeux.",a:"Robin Stern"},
{fi:"Narsisti näkee muut peileinä, ei ihmisinä.",en:"The narcissist sees others as mirrors, not people.",sv:"Narcissisten ser andra som speglar, inte människor.",es:"El narcisista ve a los demás como espejos, no como personas.",de:"Der Narzisst sieht andere als Spiegel, nicht als Menschen.",pt:"O narcisista vê os outros como espelhos, não como pessoas.",fr:"Le narcissique voit les autres comme des miroirs, pas comme des personnes.",a:"Sam Vaknin"},
{fi:"Toipuminen alkaa siitä hetkestä kun sanot: tämä ei ollut normaalia.",en:"Recovery begins when you say: this was not normal.",sv:"Återhämtning börjar när du säger: detta var inte normalt.",es:"La recuperación comienza cuando dices: esto no era normal.",de:"Genesung beginnt, wenn du sagst: Das war nicht normal.",pt:"A recuperação começa quando você diz: isso não era normal.",fr:"La guérison commence quand vous dites : ce n'était pas normal.",a:"Dr. Ramani"},
{fi:"Häpeä on narsismin polttoaine.",en:"Shame is the fuel of narcissism.",sv:"Skam är narcissismens bränsle.",es:"La vergüenza es el combustible del narcisismo.",de:"Scham ist der Treibstoff des Narzissmus.",pt:"A vergonha é o combustível do narcisismo.",fr:"La honte est le carburant du narcissisme.",a:"Brené Brown"},
{fi:"Et voi rakastaa ketään vapaaksi narsismista.",en:"You cannot love someone free of narcissism.",sv:"Du kan inte älska någon fri från narcissism.",es:"No puedes amar a alguien para liberarlo del narcisismo.",de:"Du kannst niemanden von Narzissmus freihalten.",pt:"Você não pode amar alguém para libertá-lo do narcisismo.",fr:"Vous ne pouvez pas aimer quelqu'un pour le libérer du narcissisme.",a:"Shannon Thomas"},
{fi:"Love bombing ei ole rakkautta. Se on ansalas.",en:"Love bombing is not love. It is a trap.",sv:"Love bombing är inte kärlek. Det är en fälla.",es:"El love bombing no es amor. Es una trampa.",de:"Love Bombing ist keine Liebe. Es ist eine Falle.",pt:"Love bombing não é amor. É uma armadilha.",fr:"Le love bombing n'est pas de l'amour. C'est un piège.",a:"Narcissus"},
{fi:"Manipulaattori palkitsee tottelevaisuuden ja rankaisee itsenäisyyttä.",en:"The manipulator rewards compliance and punishes independence.",sv:"Manipulatören belönar lydnad och bestraffar självständighet.",es:"El manipulador recompensa la obediencia y castiga la independencia.",de:"Der Manipulator belohnt Gehorsam und bestraft Unabhängigkeit.",pt:"O manipulador recompensa a obediência e pune a independência.",fr:"Le manipulateur récompense la soumission et punit l'indépendance.",a:"Lundy Bancroft"},
{fi:"Lapsuuden haavat eivät oikeuta aikuista satuttamaan muita.",en:"Childhood wounds do not justify hurting others as an adult.",sv:"Barndomssår rättfärdigar inte att skada andra som vuxen.",es:"Las heridas de la infancia no justifican herir a otros de adulto.",de:"Kindheitswunden rechtfertigen es nicht, als Erwachsener andere zu verletzen.",pt:"Feridas da infância não justificam machucar os outros na vida adulta.",fr:"Les blessures d'enfance ne justifient pas de blesser les autres à l'âge adulte.",a:"Alice Miller"},
{fi:"Terve ihminen ottaa vastuun. Narsisti siirtää sen.",en:"A healthy person takes responsibility. A narcissist transfers it.",sv:"En frisk person tar ansvar. En narcissist överför det.",es:"Una persona sana asume la responsabilidad. Un narcisista la transfiere.",de:"Ein gesunder Mensch übernimmt Verantwortung. Ein Narzisst überträgt sie.",pt:"Uma pessoa saudável assume a responsabilidade. Um narcisista a transfere.",fr:"Une personne saine assume la responsabilité. Un narcissique la transfère.",a:"Psykologian viisaus"},
{fi:"Hiljaisuus voi olla asetta.",en:"Silence can be a weapon.",sv:"Tystnad kan vara ett vapen.",es:"El silencio puede ser un arma.",de:"Schweigen kann eine Waffe sein.",pt:"O silêncio pode ser uma arma.",fr:"Le silence peut être une arme.",a:"Narcissus"},
{fi:"Sinun tunteesi ovat tietoa, eivät heikkous.",en:"Your feelings are information, not weakness.",sv:"Dina känslor är information, inte svaghet.",es:"Tus sentimientos son información, no debilidad.",de:"Deine Gefühle sind Information, nicht Schwäche.",pt:"Seus sentimentos são informação, não fraqueza.",fr:"Vos sentiments sont de l'information, pas de la faiblesse.",a:"Dr. Ramani"},
{fi:"Empatia on narsismin vastakohta.",en:"Empathy is the antithesis of narcissism.",sv:"Empati är narcissismens antites.",es:"La empatía es la antítesis del narcisismo.",de:"Empathie ist die Antithese des Narzissmus.",pt:"A empatia é a antítese do narcisismo.",fr:"L'empathie est l'antithèse du narcissisme.",a:"Heinz Kohut"},
{fi:"Kun et voi luottaa omaan muistiisi, olet jo menettänyt jotain arvokasta.",en:"When you can't trust your own memory, you've already lost something precious.",sv:"När du inte kan lita på ditt eget minne har du redan förlorat något värdefullt.",es:"Cuando no puedes confiar en tu propia memoria, ya has perdido algo precioso.",de:"Wenn du deinem eigenen Gedächtnis nicht trauen kannst, hast du bereits etwas Kostbares verloren.",pt:"Quando você não pode confiar na sua própria memória, já perdeu algo precioso.",fr:"Quand vous ne pouvez plus faire confiance à votre propre mémoire, vous avez déjà perdu quelque chose de précieux.",a:"Robin Stern"},
{fi:"Narsistinen suhde kuluttaa sinut tyhjäksi.",en:"A narcissistic relationship drains you hollow.",sv:"Ett narcissistiskt förhållande dränerar dig tom.",es:"Una relación narcisista te vacía por completo.",de:"Eine narzisstische Beziehung laugt dich vollständig aus.",pt:"Um relacionamento narcisista te drena até o vazio.",fr:"Une relation narcissique vous vide entièrement.",a:"Shannon Thomas"},
{fi:"Et voi täyttää pohjatonta kaivoa.",en:"You cannot fill a bottomless well.",sv:"Du kan inte fylla en bottenlös brunn.",es:"No puedes llenar un pozo sin fondo.",de:"Du kannst keinen bodenlosen Brunnen füllen.",pt:"Você não pode encher um poço sem fundo.",fr:"Vous ne pouvez pas remplir un puits sans fond.",a:"Narcissus"},
{fi:"Todellisuus ei neuvottele narsistin kanssa.",en:"Reality does not negotiate with the narcissist.",sv:"Verkligheten förhandlar inte med narcissisten.",es:"La realidad no negocia con el narcisista.",de:"Die Realität verhandelt nicht mit dem Narzissten.",pt:"A realidade não negocia com o narcisista.",fr:"La réalité ne négocie pas avec le narcissique.",a:"Sam Vaknin"},
{fi:"Mikään ei ole koskaan tarpeeksi, kun sisäinen tyhjyys on rajaton.",en:"Nothing is ever enough when the inner void is boundless.",sv:"Ingenting räcker någonsin när den inre tomheten är gränslös.",es:"Nada es nunca suficiente cuando el vacío interior es ilimitado.",de:"Nichts ist jemals genug, wenn die innere Leere grenzenlos ist.",pt:"Nada é jamais suficiente quando o vazio interior é ilimitado.",fr:"Rien n'est jamais suffisant quand le vide intérieur est sans limites.",a:"Alexander Lowen"},
{fi:"Toipuminen on matka takaisin itseesi.",en:"Recovery is a journey back to yourself.",sv:"Återhämtning är en resa tillbaka till dig själv.",es:"La recuperación es un viaje de regreso a ti mismo.",de:"Genesung ist eine Reise zurück zu dir selbst.",pt:"A recuperação é uma jornada de volta a si mesmo.",fr:"La guérison est un voyage de retour vers soi-même.",a:"Pete Walker"},
{fi:"Manipuloija käyttää rakkautesi sinua vastaan.",en:"The manipulator uses your love against you.",sv:"Manipulatören använder din kärlek mot dig.",es:"El manipulador usa tu amor en tu contra.",de:"Der Manipulator benutzt deine Liebe gegen dich.",pt:"O manipulador usa seu amor contra você.",fr:"Le manipulateur utilise votre amour contre vous.",a:"Lundy Bancroft"},
{fi:"Tietoisuus on ensimmäinen vapaus.",en:"Awareness is the first freedom.",sv:"Medvetenhet är den första friheten.",es:"La conciencia es la primera libertad.",de:"Bewusstsein ist die erste Freiheit.",pt:"A consciência é a primeira liberdade.",fr:"La prise de conscience est la première liberté.",a:"Narcissus"},
{fi:"Narsisti rakastaa ihannettaan sinusta, ei sinua.",en:"The narcissist loves their ideal of you, not you.",sv:"Narcissisten älskar sin idealbild av dig, inte dig.",es:"El narcisista ama su ideal de ti, no a ti.",de:"Der Narzisst liebt sein Idealbild von dir, nicht dich.",pt:"O narcisista ama o ideal que tem de você, não você.",fr:"Le narcissique aime son idéal de vous, pas vous.",a:"Sam Vaknin"},
{fi:"Rajasi ovat sinun rakkauttasi itsellesi.",en:"Your boundaries are your love for yourself.",sv:"Dina gränser är din kärlek till dig själv.",es:"Tus límites son tu amor hacia ti mismo.",de:"Deine Grenzen sind deine Liebe zu dir selbst.",pt:"Seus limites são seu amor por si mesmo.",fr:"Vos limites sont votre amour pour vous-même.",a:"Nedra Glover Tawwab"},
{fi:"Kaikki alkaa siitä kun tunnistat kaavan.",en:"Everything begins when you recognize the pattern.",sv:"Allt börjar när du känner igen mönstret.",es:"Todo comienza cuando reconoces el patrón.",de:"Alles beginnt, wenn du das Muster erkennst.",pt:"Tudo começa quando você reconhece o padrão.",fr:"Tout commence quand vous reconnaissez le schéma.",a:"Dr. Ramani"},
{fi:"Ei ole sinun tehtäväsi korjata ketään.",en:"It is not your job to fix anyone.",sv:"Det är inte ditt jobb att laga någon.",es:"No es tu trabajo arreglar a nadie.",de:"Es ist nicht deine Aufgabe, jemanden zu reparieren.",pt:"Não é seu trabalho consertar ninguém.",fr:"Ce n'est pas votre travail de réparer qui que ce soit.",a:"Narcissus"},
{fi:"Lapsuuden narsistinen vanhempi jättää jäljen jota aikuinen voi parantaa.",en:"A narcissistic parent in childhood leaves a wound the adult can heal.",sv:"En narcissistisk förälder i barndomen lämnar ett sår som den vuxne kan läka.",es:"Un padre narcisista en la infancia deja una herida que el adulto puede sanar.",de:"Ein narzisstischer Elternteil in der Kindheit hinterlässt eine Wunde, die der Erwachsene heilen kann.",pt:"Um pai narcisista na infância deixa uma ferida que o adulto pode curar.",fr:"Un parent narcissique dans l'enfance laisse une blessure que l'adulte peut guérir.",a:"Alice Miller"},
{fi:"Pelko ja rakkaus eivät voi asua samassa sydämessä.",en:"Fear and love cannot live in the same heart.",sv:"Rädsla och kärlek kan inte bo i samma hjärta.",es:"El miedo y el amor no pueden vivir en el mismo corazón.",de:"Angst und Liebe können nicht im selben Herzen wohnen.",pt:"O medo e o amor não podem viver no mesmo coração.",fr:"La peur et l'amour ne peuvent pas vivre dans le même cœur.",a:"Erich Fromm"},
{fi:"Ainoa ihminen jonka voit muuttaa olet sinä itse.",en:"The only person you can change is yourself.",sv:"Den enda person du kan förändra är dig själv.",es:"La única persona que puedes cambiar eres tú mismo.",de:"Die einzige Person, die du ändern kannst, bist du selbst.",pt:"A única pessoa que você pode mudar é você mesmo.",fr:"La seule personne que vous pouvez changer, c'est vous-même.",a:"Psykologian viisaus"},
{fi:"Minäkuva, joka vaatii jatkuvaa vahvistusta, on hauras.",en:"A self-image that requires constant validation is fragile.",sv:"En självbild som kräver ständig bekräftelse är bräcklig.",es:"Una autoimagen que requiere validación constante es frágil.",de:"Ein Selbstbild, das ständige Bestätigung braucht, ist zerbrechlich.",pt:"Uma autoimagem que requer validação constante é frágil.",fr:"Une image de soi qui nécessite une validation constante est fragile.",a:"Heinz Kohut"},
{fi:"Triangulaatio on kolmen pelaajan peli jossa sinä häviät.",en:"Triangulation is a three-player game where you lose.",sv:"Triangulering är ett spel med tre spelare där du förlorar.",es:"La triangulación es un juego de tres jugadores donde tú pierdes.",de:"Triangulation ist ein Spiel mit drei Spielern, bei dem du verlierst.",pt:"A triangulação é um jogo de três jogadores onde você perde.",fr:"La triangulation est un jeu à trois joueurs où vous perdez.",a:"Narcissus"},
{fi:"DARVO on narsistin hätäpoistumistie.",en:"DARVO is the narcissist's emergency exit.",sv:"DARVO är narcissistens nödutgång.",es:"DARVO es la salida de emergencia del narcisista.",de:"DARVO ist der Notausgang des Narzissten.",pt:"DARVO é a saída de emergência do narcisista.",fr:"DARVO est la sortie de secours du narcissique.",a:"Jennifer Freyd"},
{fi:"Oikea rakkaus kasvaa hitaasti.",en:"Real love grows slowly.",sv:"Äkta kärlek växer långsamt.",es:"El amor verdadero crece lentamente.",de:"Wahre Liebe wächst langsam.",pt:"O amor verdadeiro cresce devagar.",fr:"Le vrai amour grandit lentement.",a:"Erich Fromm"},
{fi:"Sinä et ole liian herkkä. He ovat liian kovia.",en:"You are not too sensitive. They are too hard.",sv:"Du är inte för känslig. De är för hårda.",es:"No eres demasiado sensible. Ellos son demasiado duros.",de:"Du bist nicht zu empfindlich. Sie sind zu hart.",pt:"Você não é sensível demais. Eles são duros demais.",fr:"Vous n'êtes pas trop sensible. Ce sont eux qui sont trop durs.",a:"Dr. Ramani"},
{fi:"Trauma on kehon muisti.",en:"Trauma is the body's memory.",sv:"Trauma är kroppens minne.",es:"El trauma es la memoria del cuerpo.",de:"Trauma ist das Gedächtnis des Körpers.",pt:"O trauma é a memória do corpo.",fr:"Le traumatisme est la mémoire du corps.",a:"Pete Walker"},
{fi:"Narsistinen häpeä piiloutuu ylimielisyyden taakse.",en:"Narcissistic shame hides behind arrogance.",sv:"Narcissistisk skam gömmer sig bakom arrogans.",es:"La vergüenza narcisista se esconde detrás de la arrogancia.",de:"Narzisstische Scham versteckt sich hinter Arroganz.",pt:"A vergonha narcisista se esconde atrás da arrogância.",fr:"La honte narcissique se cache derrière l'arrogance.",a:"Brené Brown"},
{fi:"Älä selitä itseäsi niille jotka eivät halua ymmärtää.",en:"Don't explain yourself to those who don't want to understand.",sv:"Förklara inte dig själv för dem som inte vill förstå.",es:"No te expliques ante quienes no quieren entender.",de:"Erkläre dich nicht denen, die nicht verstehen wollen.",pt:"Não se explique para quem não quer entender.",fr:"Ne vous expliquez pas à ceux qui ne veulent pas comprendre.",a:"Narcissus"},
{fi:"Hoovering on narsistin taikatemppua.",en:"Hoovering is the narcissist's magic trick.",sv:"Hoovering är narcissistens trollkonst.",es:"El hoovering es el truco de magia del narcisista.",de:"Hoovering ist der Zaubertrick des Narzissten.",pt:"Hoovering é o truque de mágica do narcisista.",fr:"Le hoovering est le tour de magie du narcissique.",a:"Jackson MacKenzie"},
{fi:"Sinun tarpeesi ovat yhtä tärkeitä kuin kenenkään muun.",en:"Your needs are just as important as anyone else's.",sv:"Dina behov är lika viktiga som alla andras.",es:"Tus necesidades son tan importantes como las de cualquier otra persona.",de:"Deine Bedürfnisse sind genauso wichtig wie die aller anderen.",pt:"Suas necessidades são tão importantes quanto as de qualquer outra pessoa.",fr:"Vos besoins sont tout aussi importants que ceux de n'importe qui d'autre.",a:"Nedra Glover Tawwab"},
{fi:"Pelastaminen ei ole rakkaus. Rakkaus on kunnioitus.",en:"Saving is not love. Love is respect.",sv:"Att rädda är inte kärlek. Kärlek är respekt.",es:"Salvar no es amor. El amor es respeto.",de:"Retten ist nicht Liebe. Liebe ist Respekt.",pt:"Salvar não é amor. Amor é respeito.",fr:"Sauver n'est pas aimer. L'amour est respect.",a:"Erich Fromm"},
{fi:"Projektiossa tekijä näkee omat pahimmat piirteensä uhrissa.",en:"In projection, the abuser sees their worst traits in the victim.",sv:"I projektion ser förövaren sina värsta drag hos offret.",es:"En la proyección, el abusador ve sus peores rasgos en la víctima.",de:"Bei der Projektion sieht der Täter seine schlimmsten Eigenschaften im Opfer.",pt:"Na projeção, o abusador vê seus piores traços na vítima.",fr:"Dans la projection, l'agresseur voit ses pires traits chez la victime.",a:"Shahida Arabi"},
{fi:"Toipuminen ei ole lineaarista. Se on aaltoilevaa.",en:"Recovery is not linear. It is wavelike.",sv:"Återhämtning är inte linjär. Den är våglik.",es:"La recuperación no es lineal. Es ondulante.",de:"Genesung ist nicht linear. Sie verläuft wellenförmig.",pt:"A recuperação não é linear. É ondulante.",fr:"La guérison n'est pas linéaire. Elle est ondulante.",a:"Pete Walker"},
{fi:"Empatiakyvyttömyys tekee suhteesta mahdottoman.",en:"The inability to empathize makes a relationship impossible.",sv:"Oförmågan att känna empati gör ett förhållande omöjligt.",es:"La incapacidad de empatizar hace imposible una relación.",de:"Die Unfähigkeit zu empfinden macht eine Beziehung unmöglich.",pt:"A incapacidade de ter empatia torna um relacionamento impossível.",fr:"L'incapacité d'éprouver de l'empathie rend une relation impossible.",a:"Craig Malkin"},
{fi:"Et voi neuvotella paremman kohtelun puolesta narsistin kanssa.",en:"You cannot negotiate for better treatment with a narcissist.",sv:"Du kan inte förhandla om bättre behandling med en narcissist.",es:"No puedes negociar un mejor trato con un narcisista.",de:"Du kannst nicht mit einem Narzissten über bessere Behandlung verhandeln.",pt:"Você não pode negociar um tratamento melhor com um narcisista.",fr:"Vous ne pouvez pas négocier un meilleur traitement avec un narcissique.",a:"Dr. Ramani"},
{fi:"Itsetunto ei ole arroganssia. Se on tasapainoa.",en:"Self-esteem is not arrogance. It is balance.",sv:"Självkänsla är inte arrogans. Det är balans.",es:"La autoestima no es arrogancia. Es equilibrio.",de:"Selbstwertgefühl ist nicht Arroganz. Es ist Gleichgewicht.",pt:"Autoestima não é arrogância. É equilíbrio.",fr:"L'estime de soi n'est pas de l'arrogance. C'est de l'équilibre.",a:"Heinz Kohut"},
{fi:"Muutos alkaa siitä kun lopetit itsesi syyttämisen.",en:"Change begins when you stopped blaming yourself.",sv:"Förändring börjar när du slutar skylla på dig själv.",es:"El cambio comienza cuando dejas de culparte a ti mismo.",de:"Veränderung beginnt, wenn du aufhörst, dir die Schuld zu geben.",pt:"A mudança começa quando você para de se culpar.",fr:"Le changement commence quand vous cessez de vous blâmer.",a:"Narcissus"},
{fi:"Kipuasi ei voi mitata. Se on todellinen.",en:"Your pain cannot be measured. It is real.",sv:"Din smärta kan inte mätas. Den är verklig.",es:"Tu dolor no se puede medir. Es real.",de:"Dein Schmerz lässt sich nicht messen. Er ist real.",pt:"Sua dor não pode ser medida. Ela é real.",fr:"Votre douleur ne peut pas être mesurée. Elle est réelle.",a:"Shannon Thomas"},
{fi:"Manipulaattori tekee sinut riippuvaiseksi heidän todellisuudestaan.",en:"The manipulator makes you dependent on their reality.",sv:"Manipulatören gör dig beroende av deras verklighet.",es:"El manipulador te hace dependiente de su realidad.",de:"Der Manipulator macht dich abhängig von seiner Realität.",pt:"O manipulador faz você depender da realidade dele.",fr:"Le manipulateur vous rend dépendant de sa réalité.",a:"Lundy Bancroft"},
{fi:"Narsisti idealisoi, devalvoi, hylkää. Toistaa.",en:"The narcissist idealizes, devalues, discards. Repeats.",sv:"Narcissisten idealiserar, devalverar, förkastar. Upprepar.",es:"El narcisista idealiza, devalúa, descarta. Repite.",de:"Der Narzisst idealisiert, entwertet, verwirft. Wiederholt.",pt:"O narcisista idealiza, desvaloriza, descarta. Repete.",fr:"Le narcissique idéalise, dévalorise, rejette. Répète.",a:"Sam Vaknin"},
{fi:"Tuntemus siitä, että olet hullu, on usein merkki gaslightingista.",en:"The feeling that you're going crazy is often a sign of gaslighting.",sv:"Känslan av att du håller på att bli galen är ofta ett tecken på gaslighting.",es:"La sensación de que te estás volviendo loco es a menudo una señal de gaslighting.",de:"Das Gefühl, verrückt zu werden, ist oft ein Zeichen von Gaslighting.",pt:"A sensação de que você está enlouquecendo é frequentemente um sinal de gaslighting.",fr:"Le sentiment de devenir fou est souvent un signe de gaslighting.",a:"Robin Stern"},
{fi:"Rakkaus ei saisi tuntua taistelulta.",en:"Love should not feel like a battle.",sv:"Kärlek borde inte kännas som en kamp.",es:"El amor no debería sentirse como una batalla.",de:"Liebe sollte sich nicht wie ein Kampf anfühlen.",pt:"O amor não deveria parecer uma batalha.",fr:"L'amour ne devrait pas ressembler à une bataille.",a:"Narcissus"},
{fi:"Vastuuttomuus ei katoa rakastamalla.",en:"Irresponsibility doesn't disappear with love.",sv:"Ansvarslöshet försvinner inte med kärlek.",es:"La irresponsabilidad no desaparece con amor.",de:"Verantwortungslosigkeit verschwindet nicht durch Liebe.",pt:"A irresponsabilidade não desaparece com amor.",fr:"L'irresponsabilité ne disparaît pas avec l'amour.",a:"Lundy Bancroft"},
{fi:"Sinun arvokkuutesi ei riipu kenenkään hyväksynnästä.",en:"Your worth does not depend on anyone's approval.",sv:"Ditt värde beror inte på någons godkännande.",es:"Tu valor no depende de la aprobación de nadie.",de:"Dein Wert hängt nicht von der Zustimmung anderer ab.",pt:"Seu valor não depende da aprovação de ninguém.",fr:"Votre valeur ne dépend de l'approbation de personne.",a:"Brené Brown"},
{fi:"Toinen ihminen ei voi täyttää sitä aukkoa, jonka sinä jätät itsessäsi.",en:"Another person cannot fill the gap you leave within yourself.",sv:"En annan person kan inte fylla det tomrum du lämnar inom dig själv.",es:"Otra persona no puede llenar el vacío que tú dejas dentro de ti.",de:"Ein anderer Mensch kann die Lücke nicht füllen, die du in dir selbst hinterlässt.",pt:"Outra pessoa não pode preencher o vazio que você deixa dentro de si.",fr:"Une autre personne ne peut pas combler le vide que vous laissez en vous-même.",a:"Erich Fromm"},
{fi:"Narsistinen äiti tai isä opettaa lapselle: rakkaus on ehdollista.",en:"A narcissistic mother or father teaches a child: love is conditional.",sv:"En narcissistisk mor eller far lär barnet: kärlek är villkorad.",es:"Un padre o madre narcisista enseña al niño: el amor es condicional.",de:"Eine narzisstische Mutter oder ein narzisstischer Vater lehrt das Kind: Liebe ist an Bedingungen geknüpft.",pt:"Uma mãe ou pai narcisista ensina à criança: o amor é condicional.",fr:"Un père ou une mère narcissique enseigne à l'enfant : l'amour est conditionnel.",a:"Alice Miller"},
{fi:"Haavoittuva narsismi kätkeytyy uhriuden taakse.",en:"Vulnerable narcissism hides behind victimhood.",sv:"Sårbar narcissism gömmer sig bakom offerskap.",es:"El narcisismo vulnerable se esconde detrás de la victimización.",de:"Verletzlicher Narzissmus versteckt sich hinter Opferhaltung.",pt:"O narcisismo vulnerável se esconde atrás da vitimização.",fr:"Le narcissisme vulnérable se cache derrière la victimisation.",a:"Craig Malkin"},
{fi:"Grey rock: ole niin tylsä, ettei manipulaattori vaivaudu.",en:"Grey rock: be so boring the manipulator won't bother.",sv:"Grey rock: var så tråkig att manipulatören inte bryr sig.",es:"Grey rock: sé tan aburrido que el manipulador no se moleste.",de:"Grey Rock: Sei so langweilig, dass der Manipulator sich nicht die Mühe macht.",pt:"Grey rock: seja tão entediante que o manipulador não se incomode.",fr:"Grey rock : soyez si ennuyeux que le manipulateur ne se donnera pas la peine.",a:"Narcissus"},
{fi:"Sinä et ole vastuussa toisen tunteista.",en:"You are not responsible for someone else's feelings.",sv:"Du är inte ansvarig för någon annans känslor.",es:"No eres responsable de los sentimientos de otra persona.",de:"Du bist nicht verantwortlich für die Gefühle anderer.",pt:"Você não é responsável pelos sentimentos de outra pessoa.",fr:"Vous n'êtes pas responsable des sentiments de quelqu'un d'autre.",a:"Nedra Glover Tawwab"},
{fi:"Suhteen alun intensiteetti ei ole rakkautta – se on merkki.",en:"The intensity at the start of a relationship is not love – it's a sign.",sv:"Intensiteten i början av ett förhållande är inte kärlek – det är ett varningstecken.",es:"La intensidad al inicio de una relación no es amor – es una señal.",de:"Die Intensität am Anfang einer Beziehung ist keine Liebe – es ist ein Warnzeichen.",pt:"A intensidade no início de um relacionamento não é amor – é um sinal.",fr:"L'intensité au début d'une relation n'est pas de l'amour – c'est un signal d'alarme.",a:"Jackson MacKenzie"},
{fi:"Kognitiivinen dissonanssi pitää meidät loukkussa.",en:"Cognitive dissonance keeps us trapped.",sv:"Kognitiv dissonans håller oss fångade.",es:"La disonancia cognitiva nos mantiene atrapados.",de:"Kognitive Dissonanz hält uns gefangen.",pt:"A dissonância cognitiva nos mantém presos.",fr:"La dissonance cognitive nous maintient piégés.",a:"Shahida Arabi"},
{fi:"Et ansaitse kipua jota saat. Et ansaitse sitä.",en:"You don't deserve the pain you receive. You don't deserve it.",sv:"Du förtjänar inte smärtan du får. Du förtjänar det inte.",es:"No mereces el dolor que recibes. No lo mereces.",de:"Du verdienst nicht den Schmerz, den du erhältst. Du verdienst ihn nicht.",pt:"Você não merece a dor que recebe. Você não merece isso.",fr:"Vous ne méritez pas la douleur que vous recevez. Vous ne la méritez pas.",a:"Dr. Ramani"},
{fi:"Vapaus alkaa siitä kun et enää tarvitse heidän hyväksyntäänsä.",en:"Freedom begins when you no longer need their approval.",sv:"Frihet börjar när du inte längre behöver deras godkännande.",es:"La libertad comienza cuando ya no necesitas su aprobación.",de:"Freiheit beginnt, wenn du ihre Zustimmung nicht mehr brauchst.",pt:"A liberdade começa quando você não precisa mais da aprovação deles.",fr:"La liberté commence quand vous n'avez plus besoin de leur approbation.",a:"Narcissus"},
{fi:"Traumasidos sitoo uhrin hyväksikäyttäjäänsä.",en:"The trauma bond ties the victim to the abuser.",sv:"Traumabandet binder offret till förövaren.",es:"El vínculo traumático ata a la víctima con el abusador.",de:"Die Traumabindung fesselt das Opfer an den Täter.",pt:"O vínculo traumático prende a vítima ao abusador.",fr:"Le lien traumatique attache la victime à l'agresseur.",a:"Patrick Carnes"},
{fi:"Narsisti ei koe syyllisyyttä – vain häpeää ja sen pelkoa.",en:"The narcissist doesn't feel guilt – only shame and the fear of it.",sv:"Narcissisten känner inte skuld – bara skam och rädslan för den.",es:"El narcisista no siente culpa – solo vergüenza y el miedo a ella.",de:"Der Narzisst empfindet keine Schuld – nur Scham und die Angst davor.",pt:"O narcisista não sente culpa – apenas vergonha e o medo dela.",fr:"Le narcissique ne ressent pas de culpabilité – seulement la honte et la peur de celle-ci.",a:"Sam Vaknin"},
{fi:"Kasvaminen on kivuliasta mutta pysähtyminen on tuhoisampaa.",en:"Growing is painful but stagnating is more destructive.",sv:"Att växa är smärtsamt men att stagnera är mer destruktivt.",es:"Crecer es doloroso pero estancarse es más destructivo.",de:"Wachsen ist schmerzhaft, aber Stillstand ist zerstörerischer.",pt:"Crescer é doloroso, mas estagnar é mais destrutivo.",fr:"Grandir est douloureux mais stagner est plus destructeur.",a:"Marcus Aurelius"},
{fi:"Opi tuntemaan rauhasi arvo.",en:"Learn to know the value of your peace.",sv:"Lär dig känna värdet av din frid.",es:"Aprende a conocer el valor de tu paz.",de:"Lerne den Wert deines Friedens kennen.",pt:"Aprenda a conhecer o valor da sua paz.",fr:"Apprenez à connaître la valeur de votre paix.",a:"Seneca"},
{fi:"Tunteiden tukahduttaminen ei poista niitä.",en:"Suppressing emotions doesn't eliminate them.",sv:"Att undertrycka känslor eliminerar dem inte.",es:"Reprimir las emociones no las elimina.",de:"Gefühle zu unterdrücken beseitigt sie nicht.",pt:"Reprimir emoções não as elimina.",fr:"Réprimer les émotions ne les élimine pas.",a:"Pete Walker"},
{fi:"Joka hetki on uusi mahdollisuus valita eri tavalla.",en:"Every moment is a new chance to choose differently.",sv:"Varje ögonblick är en ny chans att välja annorlunda.",es:"Cada momento es una nueva oportunidad de elegir diferente.",de:"Jeder Moment ist eine neue Chance, anders zu wählen.",pt:"Cada momento é uma nova chance de escolher diferente.",fr:"Chaque instant est une nouvelle chance de choisir autrement.",a:"Marcus Aurelius"},
{fi:"Elä niin, että voit katsoa itseäsi peiliin.",en:"Live so that you can look at yourself in the mirror.",sv:"Lev så att du kan se dig själv i spegeln.",es:"Vive de manera que puedas mirarte al espejo.",de:"Lebe so, dass du dich im Spiegel ansehen kannst.",pt:"Viva de modo que possa se olhar no espelho.",fr:"Vivez de sorte que vous puissiez vous regarder dans le miroir.",a:"Seneca"},
{fi:"Todellinen voima ei tarvitse väkivaltaa.",en:"Real strength needs no violence.",sv:"Verklig styrka behöver inget våld.",es:"La verdadera fuerza no necesita violencia.",de:"Wahre Stärke braucht keine Gewalt.",pt:"A verdadeira força não precisa de violência.",fr:"La vraie force n'a pas besoin de violence.",a:"Lao Tse"},
{fi:"Rakkaus ilman vapaat ei ole rakkautta.",en:"Love without freedom is not love.",sv:"Kärlek utan frihet är inte kärlek.",es:"El amor sin libertad no es amor.",de:"Liebe ohne Freiheit ist keine Liebe.",pt:"Amor sem liberdade não é amor.",fr:"L'amour sans liberté n'est pas de l'amour.",a:"Erich Fromm"},
{fi:"Kipu on opettaja jota kukaan ei pyydä mutta kaikki tarvitsevat.",en:"Pain is a teacher nobody asks for but everyone needs.",sv:"Smärta är en lärare ingen ber om men alla behöver.",es:"El dolor es un maestro que nadie pide pero todos necesitan.",de:"Schmerz ist ein Lehrer, den niemand bittet, aber jeder braucht.",pt:"A dor é um professor que ninguém pede mas todos precisam.",fr:"La douleur est un professeur que personne ne demande mais dont tout le monde a besoin.",a:"Rumi"},
{fi:"Itsetunto rakennetaan teoilla, ei sanoilla.",en:"Self-esteem is built through actions, not words.",sv:"Självkänsla byggs genom handlingar, inte ord.",es:"La autoestima se construye con acciones, no con palabras.",de:"Selbstwertgefühl wird durch Taten aufgebaut, nicht durch Worte.",pt:"A autoestima é construída por ações, não por palavras.",fr:"L'estime de soi se construit par les actes, pas par les mots.",a:"Aristoteles"},
{fi:"Epätoivo on tie muutokseen.",en:"Despair is the road to change.",sv:"Förtvivlan är vägen till förändring.",es:"La desesperación es el camino hacia el cambio.",de:"Verzweiflung ist der Weg zur Veränderung.",pt:"O desespero é o caminho para a mudança.",fr:"Le désespoir est le chemin du changement.",a:"Kierkegaard"},
{fi:"Minuus joka ei kykene rakastamaan on tyhjä.",en:"A self incapable of love is empty.",sv:"Ett jag som inte kan älska är tomt.",es:"Un yo incapaz de amar está vacío.",de:"Ein Selbst, das nicht lieben kann, ist leer.",pt:"Um eu incapaz de amar é vazio.",fr:"Un moi incapable d'aimer est vide.",a:"Erich Fromm"},
{fi:"Hyvä elämä alkaa siitä kun lakkaat elämästä toisten odotusten mukaan.",en:"The good life begins when you stop living by others' expectations.",sv:"Det goda livet börjar när du slutar leva efter andras förväntningar.",es:"La buena vida comienza cuando dejas de vivir según las expectativas de los demás.",de:"Das gute Leben beginnt, wenn du aufhörst, nach den Erwartungen anderer zu leben.",pt:"A boa vida começa quando você para de viver pelas expectativas dos outros.",fr:"La bonne vie commence quand vous cessez de vivre selon les attentes des autres.",a:"Aristoteles"},
{fi:"Katso suoraan sitä mitä pelkäät.",en:"Look directly at what you fear.",sv:"Se rakt på det du fruktar.",es:"Mira directamente lo que temes.",de:"Schau direkt auf das, was du fürchtest.",pt:"Olhe diretamente para o que você teme.",fr:"Regardez directement ce que vous craignez.",a:"Nietzsche"},
{fi:"Vapaus on sisäistä, ei ulkoista.",en:"Freedom is internal, not external.",sv:"Frihet är inre, inte yttre.",es:"La libertad es interna, no externa.",de:"Freiheit ist innerlich, nicht äußerlich.",pt:"A liberdade é interna, não externa.",fr:"La liberté est intérieure, pas extérieure.",a:"Seneca"},
{fi:"Jokainen haava on merkki selviytymisestä.",en:"Every wound is a mark of survival.",sv:"Varje sår är ett märke av överlevnad.",es:"Cada herida es una marca de supervivencia.",de:"Jede Wunde ist ein Zeichen des Überlebens.",pt:"Cada ferida é uma marca de sobrevivência.",fr:"Chaque blessure est une marque de survie.",a:"Rumi"},
{fi:"Heikko ihminen rankaisee, vahva ihminen antaa anteeksi.",en:"A weak person punishes, a strong person forgives.",sv:"En svag person straffar, en stark person förlåter.",es:"Una persona débil castiga, una persona fuerte perdona.",de:"Ein schwacher Mensch bestraft, ein starker Mensch vergibt.",pt:"Uma pessoa fraca pune, uma pessoa forte perdoa.",fr:"Une personne faible punit, une personne forte pardonne.",a:"Marcus Aurelius"},
{fi:"Virhe jota et myönnä jää sinulle kahleeksi.",en:"A mistake you don't admit becomes a chain.",sv:"Ett misstag du inte erkänner blir en kedja.",es:"Un error que no admites se convierte en una cadena.",de:"Ein Fehler, den du nicht zugibst, wird zu einer Kette.",pt:"Um erro que você não admite se torna uma corrente.",fr:"Une erreur que vous n'admettez pas devient une chaîne.",a:"Nietzsche"},
{fi:"Toimi oikein, vaikka kukaan ei näe.",en:"Do right, even when no one is watching.",sv:"Gör rätt, även när ingen ser.",es:"Haz lo correcto, incluso cuando nadie mira.",de:"Handle richtig, auch wenn niemand zuschaut.",pt:"Faça o certo, mesmo quando ninguém está olhando.",fr:"Faites le bien, même quand personne ne regarde.",a:"Marcus Aurelius"},
{fi:"Minulla on oikeus omaan todellisuuteeni.",en:"I have a right to my own reality.",sv:"Jag har rätt till min egen verklighet.",es:"Tengo derecho a mi propia realidad.",de:"Ich habe ein Recht auf meine eigene Realität.",pt:"Eu tenho direito à minha própria realidade.",fr:"J'ai le droit à ma propre réalité.",a:"Narcissus"},
{fi:"Narsistinen kontrolloinit tarvitsee reaktiosi – älä anna sitä.",en:"Narcissistic control needs your reaction – don't give it.",sv:"Narcissistisk kontroll behöver din reaktion – ge den inte.",es:"El control narcisista necesita tu reacción – no la des.",de:"Narzisstische Kontrolle braucht deine Reaktion – gib sie nicht.",pt:"O controle narcisista precisa da sua reação – não a dê.",fr:"Le contrôle narcissique a besoin de votre réaction – ne la donnez pas.",a:"Narcissus"},
{fi:"Toivuttuasi tunnistat varoitusmerkit ennen kuin astunut loukkuun.",en:"Once recovered, you recognize warning signs before stepping into the trap.",sv:"När du har återhämtat dig känner du igen varningstecknen innan du kliver i fällan.",es:"Una vez recuperado, reconoces las señales de alerta antes de caer en la trampa.",de:"Nach der Genesung erkennst du die Warnsignale, bevor du in die Falle trittst.",pt:"Uma vez recuperado, você reconhece os sinais de alerta antes de cair na armadilha.",fr:"Une fois guéri, vous reconnaissez les signes d'alerte avant de tomber dans le piège.",a:"Shahida Arabi"},
{fi:"Suhteen kaunein hetki on luottamuksen syvyydessä.",en:"The most beautiful moment in a relationship is in the depth of trust.",sv:"Det vackraste ögonblicket i ett förhållande är i djupet av förtroende.",es:"El momento más hermoso en una relación está en la profundidad de la confianza.",de:"Der schönste Moment in einer Beziehung liegt in der Tiefe des Vertrauens.",pt:"O momento mais bonito em um relacionamento está na profundidade da confiança.",fr:"Le plus beau moment dans une relation se trouve dans la profondeur de la confiance.",a:"Erich Fromm"},
{fi:"Itsensä tunteminen on kaiken rakkauden perusta.",en:"Self-knowledge is the foundation of all love.",sv:"Självkännedom är grunden för all kärlek.",es:"El autoconocimiento es la base de todo amor.",de:"Selbsterkenntnis ist die Grundlage aller Liebe.",pt:"O autoconhecimento é a base de todo amor.",fr:"La connaissance de soi est le fondement de tout amour.",a:"Aristoteles"},
{fi:"Et ole rikki. Sinulle on tehty rikki.",en:"You are not broken. You were broken.",sv:"Du är inte trasig. Du blev trasig.",es:"No estás roto. Te rompieron.",de:"Du bist nicht zerbrochen. Man hat dich zerbrochen.",pt:"Você não está quebrado. Quebraram você.",fr:"Vous n'êtes pas brisé. On vous a brisé.",a:"Dr. Ramani"},
{fi:"Parantuminen vaatii, että kohtaat mitä tapahtui.",en:"Healing requires you to face what happened.",sv:"Läkning kräver att du möter det som hände.",es:"La sanación requiere que enfrentes lo que sucedió.",de:"Heilung erfordert, dass du dich dem stellst, was geschehen ist.",pt:"A cura exige que você enfrente o que aconteceu.",fr:"La guérison exige que vous fassiez face à ce qui s'est passé.",a:"Pete Walker"},
{fi:"Yksi terveys on parempi kuin sata väärää anteeksipyyntöä.",en:"One healthy moment is worth more than a hundred false apologies.",sv:"Ett hälsosamt ögonblick är värt mer än hundra falska ursäkter.",es:"Un momento saludable vale más que cien disculpas falsas.",de:"Ein gesunder Moment ist mehr wert als hundert falsche Entschuldigungen.",pt:"Um momento saudável vale mais que cem desculpas falsas.",fr:"Un moment sain vaut plus que cent fausses excuses.",a:"Narcissus"},
{fi:"Ei-sana on lause.",en:"No is a complete sentence.",sv:"Nej är en hel mening.",es:"No es una oración completa.",de:"Nein ist ein vollständiger Satz.",pt:"Não é uma frase completa.",fr:"Non est une phrase complète.",a:"Nedra Glover Tawwab"},
{fi:"Sinulla on lupa olla väsynyt.",en:"You have permission to be tired.",sv:"Du har tillåtelse att vara trött.",es:"Tienes permiso para estar cansado.",de:"Du hast die Erlaubnis, müde zu sein.",pt:"Você tem permissão para estar cansado.",fr:"Vous avez la permission d'être fatigué.",a:"Shannon Thomas"},
{fi:"Kun joku kertoo kuka on – usko heitä.",en:"When someone tells you who they are – believe them.",sv:"När någon berättar vem de är – tro dem.",es:"Cuando alguien te dice quién es – créele.",de:"Wenn jemand dir sagt, wer er ist – glaube ihm.",pt:"Quando alguém te diz quem é – acredite.",fr:"Quand quelqu'un vous dit qui il est – croyez-le.",a:"Maya Angelou"},
{fi:"Narsistinen suhde ei katoa unohtuessaan – se palaa.",en:"A narcissistic relationship doesn't disappear when forgotten – it returns.",sv:"Ett narcissistiskt förhållande försvinner inte när det glöms – det återvänder.",es:"Una relación narcisista no desaparece al olvidarla – regresa.",de:"Eine narzisstische Beziehung verschwindet nicht, wenn man sie vergisst – sie kehrt zurück.",pt:"Um relacionamento narcisista não desaparece quando esquecido – ele retorna.",fr:"Une relation narcissique ne disparaît pas quand on l'oublie – elle revient.",a:"Jackson MacKenzie"},
{fi:"Rajat kommunikoivat sen minkä sanat eivät saavuta.",en:"Boundaries communicate what words cannot reach.",sv:"Gränser kommunicerar det som ord inte kan nå.",es:"Los límites comunican lo que las palabras no pueden alcanzar.",de:"Grenzen kommunizieren, was Worte nicht erreichen können.",pt:"Limites comunicam o que as palavras não conseguem alcançar.",fr:"Les limites communiquent ce que les mots ne peuvent atteindre.",a:"Nedra Glover Tawwab"},
{fi:"Traumasidos tuntuu rakkaudelta mutta toimii vankilana.",en:"Trauma bonding feels like love but functions as a prison.",sv:"Traumabindning känns som kärlek men fungerar som ett fängelse.",es:"El vínculo traumático se siente como amor pero funciona como una prisión.",de:"Traumabindung fühlt sich wie Liebe an, funktioniert aber wie ein Gefängnis.",pt:"O vínculo traumático parece amor mas funciona como uma prisão.",fr:"Le lien traumatique ressemble à l'amour mais fonctionne comme une prison.",a:"Shahida Arabi"},
{fi:"Narsismin taustalla on usein syvä häpeä.",en:"Behind narcissism there is often deep shame.",sv:"Bakom narcissism finns ofta djup skam.",es:"Detrás del narcisismo a menudo hay una vergüenza profunda.",de:"Hinter Narzissmus steckt oft tiefe Scham.",pt:"Por trás do narcisismo há frequentemente uma vergonha profunda.",fr:"Derrière le narcissisme se cache souvent une honte profonde.",a:"Brené Brown"},
{fi:"Kukaan ei voi antaa sinulle sitä mitä he eivät itsellään ole.",en:"No one can give you what they don't have themselves.",sv:"Ingen kan ge dig det de inte själva har.",es:"Nadie puede darte lo que no tiene.",de:"Niemand kann dir geben, was er selbst nicht hat.",pt:"Ninguém pode te dar o que não tem.",fr:"Personne ne peut vous donner ce qu'il n'a pas lui-même.",a:"Narcissus"},
{fi:"Parantuminen on itsesi löytämistä uudelleen.",en:"Healing is finding yourself again.",sv:"Läkning är att hitta dig själv igen.",es:"Sanar es encontrarte a ti mismo de nuevo.",de:"Heilung bedeutet, sich selbst wiederzufinden.",pt:"Curar-se é encontrar-se novamente.",fr:"Guérir, c'est se retrouver soi-même.",a:"Pete Walker"},
{fi:"Tunne itsesi. Se on kaiken viisauden alku.",en:"Know yourself. That is the beginning of all wisdom.",sv:"Känn dig själv. Det är början på all visdom.",es:"Conócete a ti mismo. Ese es el principio de toda sabiduría.",de:"Erkenne dich selbst. Das ist der Anfang aller Weisheit.",pt:"Conhece-te a ti mesmo. Esse é o início de toda sabedoria.",fr:"Connais-toi toi-même. C'est le début de toute sagesse.",a:"Aristoteles"},
{fi:"Terveissä suhteissa molemmat voivat olla haavoittuvaisia.",en:"In healthy relationships both can be vulnerable.",a:"Brené Brown"},
{fi:"Narsistinen projisiointi heijastaa tekijän sisäisen maailman.",en:"Narcissistic projection reflects the abuser's inner world.",a:"Sam Vaknin"},
{fi:"Sinun ei tarvitse pelastaa ketään rakkauttasi menettämällä.",en:"You don't have to save anyone by losing yourself.",a:"Narcissus"},
{fi:"Käytös on valinta. Häiriö on selitys, ei lupa.",en:"Behavior is a choice. Disorder explains, it doesn't excuse.",a:"Dr. Ramani"},
{fi:"Toinen ihminen ei ole sinun tehtäväsi.",en:"Another person is not your assignment.",a:"Narcissus"},
{fi:"Mielen vauriot ovat yhtä todellisia kuin kehon vauriot.",en:"Mental wounds are as real as physical ones.",a:"Shahida Arabi"},
{fi:"Narsistinen viha on kontrollointikeino.",en:"Narcissistic rage is a control mechanism.",a:"Sam Vaknin"},
{fi:"Sinun paranemisesi ei tarvitse toisen suostumusta.",en:"Your healing doesn't need anyone else's permission.",a:"Dr. Ramani"},
{fi:"Rakkaus ei pyydä sinua kadottamaan itseäsi.",en:"Love does not ask you to lose yourself.",a:"Erich Fromm"},
{fi:"Terve itsekunnioitus on juuristo jonka varassa kasvat.",en:"Healthy self-respect is the root from which you grow.",a:"Aristoteles"},
{fi:"Kontrolloiva rakkauden käsite on ristiriita.",en:"A controlling concept of love is a contradiction.",a:"Erich Fromm"},
{fi:"Jokainen selviytyjä on voittaja.",en:"Every survivor is a victor.",a:"Narcissus"},
{fi:"Manipuloija oppii nopeasti mikä saa sinut taipumaan.",en:"The manipulator quickly learns what makes you bend.",a:"Lundy Bancroft"},
{fi:"Narsistinen suhde opettaa sinut epäilemään itseäsi.",en:"A narcissistic relationship teaches you to doubt yourself.",a:"Robin Stern"},
{fi:"Terve suhde perustuu turvallisuuteen, ei pelkoon.",en:"A healthy relationship is built on safety, not fear.",a:"Narcissus"},
{fi:"Anteeksiantaminen on sinua varten, ei heitä varten.",en:"Forgiveness is for you, not for them.",a:"Narcissus"},
{fi:"Vastuullisuus on kypsyyden merkki.",en:"Accountability is the mark of maturity.",a:"Psykologian viisaus"},
{fi:"Sinä et voinut valita mitä tapahtui. Voit valita mitä seuraavaksi.",en:"You could not choose what happened. You can choose what comes next.",a:"Pete Walker"},
{fi:"Narsistinen äiti ei hyväksy lasta sellaisena kuin hän on.",en:"A narcissistic mother never accepts the child as they are.",a:"Alice Miller"},
{fi:"Grandioosius peittää tyhjyyden.",en:"Grandiosity covers emptiness.",a:"Alexander Lowen"},
{fi:"Paras suoja narsismia vastaan on vahva identiteetti.",en:"The best protection against narcissism is a strong identity.",a:"Narcissus"},
{fi:"Kipusi on pätevä, vaikka kukaan ei uskoisi sinua.",en:"Your pain is valid even if no one believes you.",a:"Dr. Ramani"},
{fi:"Läheisyys ilman turvallisuutta on vaaraa, ei rakkautta.",en:"Intimacy without safety is danger, not love.",a:"Narcissus"},
{fi:"Syvä kiintymys vaatii molemminpuolista haavoittuvuutta.",en:"Deep attachment requires mutual vulnerability.",a:"Brené Brown"},
{fi:"Toipuvan ihmisen pahin vihollinen on toivo muutoksesta jota ei tule.",en:"The recovering person's worst enemy is hope for change that won't come.",a:"Jackson MacKenzie"},
{fi:"Sinä ansaitset suhteen, jossa sinua kunnioitetaan.",en:"You deserve a relationship where you are respected.",a:"Narcissus"},
{fi:"Narsismi luo kaksoissidoksen: sinä et voi pysyä etkä lähteä.",en:"Narcissism creates a double bind: you can't stay and you can't leave.",a:"Sam Vaknin"},
{fi:"Lähtö on rohkein valinta jonka voit tehdä.",en:"Leaving is the bravest choice you can make.",a:"Shahida Arabi"},
{fi:"Narsistinen ihastuminen on nopea. Rakkauden rakentaminen on hidas.",en:"Narcissistic infatuation is fast. Building love is slow.",a:"Craig Malkin"},
{fi:"Sinun ei tarvitse olla täydellinen ansaitaksesi rakkautta.",en:"You don't have to be perfect to deserve love.",a:"Brené Brown"},
{fi:"Itsemyötätunto on toipumisen välttämätön pohja.",en:"Self-compassion is the essential foundation of recovery.",a:"Kristin Neff"},
{fi:"Narsistisessa suhteessa sinä maksat heille ylistyksellä.",en:"In a narcissistic relationship you pay them with admiration.",a:"Sam Vaknin"},
{fi:"Muuta ainoa asia jonka voit muuttaa: oma reaktiosi.",en:"Change the only thing you can change: your own reaction.",a:"Marcus Aurelius"},
{fi:"Selviytymiskykysi on suurempi kuin luulet.",en:"Your resilience is greater than you think.",a:"Narcissus"},
{fi:"Toipuminen tarkoittaa oppia elämään totuuden kanssa.",en:"Recovery means learning to live with the truth.",a:"Pete Walker"},
{fi:"Narsistin kiitos on aina ehdollinen.",en:"The narcissist's gratitude is always conditional.",a:"Sam Vaknin"},
{fi:"Häpeä ei ole sinun – se siirrettiin sinulle.",en:"Shame is not yours – it was transferred to you.",a:"Brené Brown"},
{fi:"Vapautesi uhka on heidän vastauksensa kontrolloida sinua.",en:"Your freedom is their trigger to control you.",a:"Narcissus"},
{fi:"Tieto suojelee.",en:"Knowledge protects.",a:"Narcissus"},
{fi:"Narsistin anteeksipyyntö on taktinen, ei aito.",en:"The narcissist's apology is tactical, not genuine.",a:"Dr. Ramani"},
{fi:"Oman elämänsä asiantuntija on sinä itse.",en:"The expert on your own life is you.",a:"Narcissus"},
{fi:"Kukaan ei voi ottaa sinulta sitä mitä sinulle kuuluu sisältäpäin.",en:"No one can take from you what belongs to you within.",a:"Seneca"},
{fi:"Väsymys on merkki siitä, että olet kantanut liikaa.",en:"Exhaustion is a sign that you've been carrying too much.",a:"Shannon Thomas"},
{fi:"Paras kostosi on hyvinvointisi.",en:"The best revenge is your own well-being.",a:"Narcissus"},
{fi:"Vastuu ei jakaudu tasapuolisesti narsistisessa suhteessa.",en:"Responsibility is not shared equally in a narcissistic relationship.",a:"Lundy Bancroft"},
{fi:"Olet enemmän kuin mitä heille annoit.",en:"You are more than what you gave them.",a:"Shahida Arabi"},
{fi:"Itsetuntemuksen puute on narsismin ydin.",en:"Lack of self-knowledge is the core of narcissism.",a:"Karen Horney"},
{fi:"Suhteet, joissa ei voi virheillä, eivät ole turvallisia.",en:"Relationships where mistakes aren't allowed aren't safe.",a:"Narcissus"},
{fi:"Parantuminen ei tapahdu yhdessä yössä.",en:"Healing doesn't happen overnight.",a:"Pete Walker"},
{fi:"Riippuvuus ei ole rakkautta.",en:"Dependency is not love.",a:"Erich Fromm"},
{fi:"Narsismi on itsensä epäonnistuminen rakastaa.",en:"Narcissism is the failure to love oneself.",a:"Erich Fromm"},
{fi:"Sinulla on oikeus muuttua ilman selittelyjä.",en:"You have the right to change without explanations.",a:"Narcissus"},
{fi:"Neurotiikonarsismi piiloutuu perfektionismin taakse.",en:"Neurotic narcissism hides behind perfectionism.",a:"Karen Horney"},
{fi:"Yhteys on terveyden merkki, eristys on vaaran merkki.",en:"Connection is a sign of health, isolation is a sign of danger.",a:"Brené Brown"},
{fi:"Narsisti kertoo kuka hän on käytöksellään, ei sanoillaan.",en:"The narcissist tells you who they are through behavior, not words.",a:"Dr. Ramani"},
{fi:"Sinä pystyt rakastamaan itseäsi takaisin täydeksi.",en:"You can love yourself back to wholeness.",a:"Narcissus"},
{fi:"Henkinen väkivalta jättää näkymättömät arvet.",en:"Emotional abuse leaves invisible scars.",a:"Shahida Arabi"},
{fi:"Manipulaattori ei muutu sinun tähden.",en:"The manipulator does not change for you.",a:"Lundy Bancroft"},
{fi:"Et ole vastuussa heidän lapsuudestaan.",en:"You are not responsible for their childhood.",a:"Dr. Ramani"},
{fi:"Jokainen raja jonka asetat on itsesi puolesta.",en:"Every boundary you set is standing for yourself.",a:"Nedra Glover Tawwab"},
{fi:"Selkeys on myötätunto itsellesi.",en:"Clarity is compassion for yourself.",a:"Narcissus"},
{fi:"Narsisti tarvitsee yleisön, ei kumppania.",en:"The narcissist needs an audience, not a partner.",a:"Sam Vaknin"},
{fi:"Turvallisuus ei ole tuntematon ympäristö – se on tuttu itsesi.",en:"Safety is not an unfamiliar place – it is the familiar self.",a:"Pete Walker"},
{fi:"Voimasi löytyy sieltä mistä olet eniten haavottunut.",en:"Your power is found where you were most wounded.",a:"Rumi"},
{fi:"Toipuminen on itsesi luvan antamista.",en:"Recovery is giving yourself permission.",a:"Narcissus"},
{fi:"Emotionaalinen kypsyys on toisen kivun tunnistamista.",en:"Emotional maturity is recognizing another's pain.",a:"Heinz Kohut"},
{fi:"Narsistinen suhde ei lopu eroon – se siirtyy traumaan.",en:"A narcissistic relationship doesn't end with the breakup – it moves into trauma.",a:"Jackson MacKenzie"},
{fi:"Ymmärrys ei ole anteeksiantamista.",en:"Understanding is not forgiving.",a:"Narcissus"},
{fi:"Sinulla on oikeus olla epätäydellinen.",en:"You have the right to be imperfect.",a:"Brené Brown"},
{fi:"Sinun tunteet ovat päteviä.",en:"Your feelings are valid.",a:"Narcissus"},
{fi:"Käytös joka loukkaa ei muutu, jos se toimii.",en:"Behavior that hurts doesn't change if it works.",a:"Lundy Bancroft"},
{fi:"Tarttuminen on vain toinen nimi pelkäämiselle.",en:"Clinging is just another name for fear.",a:"Lao Tse"},
{fi:"Parantuminen on kyky olla oma todistajasi.",en:"Healing is the ability to be your own witness.",a:"Pete Walker"},
{fi:"Rakkauden alkuhuuma voi piilottaa todellisen luonteen.",en:"The initial rush of love can hide the true nature.",a:"Craig Malkin"},
{fi:"Narsistinen suhde muuttaa sinut, jos et vahtaa rajojasi.",en:"A narcissistic relationship transforms you if you don't guard your boundaries.",a:"Shahida Arabi"},
{fi:"Sisäinen äänesi tietää.",en:"Your inner voice knows.",a:"Narcissus"},
{fi:"Kukaan ei ansaitse jatkuvaa kritiikkiä.",en:"No one deserves constant criticism.",a:"Dr. Ramani"},
{fi:"Tunteiden nimeäminen vie niiden voimaa.",en:"Naming emotions takes away their power.",a:"Brené Brown"},
{fi:"Kuuntele vaistoasi.",en:"Listen to your instinct.",a:"Narcissus"},
{fi:"Ehdoton rakkaus ei tarkoita rajatonta sietämistä.",en:"Unconditional love does not mean unlimited tolerance.",a:"Narcissus"},
{fi:"Toipuminen on oppia luottamaan itseään uudelleen.",en:"Recovery is learning to trust yourself again.",a:"Pete Walker"},
{fi:"Aito anteeksipyyntö ei sisällä ehtoja.",en:"A genuine apology contains no conditions.",a:"Narcissus"},
{fi:"Narsisti elää pelon varassa – pelko häpeästä.",en:"The narcissist lives on fear – fear of shame.",a:"Sam Vaknin"},
{fi:"Paraneminen on epämukava mutta välttämätön reitti.",en:"Healing is an uncomfortable but necessary path.",a:"Shahida Arabi"},
{fi:"Lakkaa selittelemästä itsellesi miksi he käyttäytyvät niin.",en:"Stop explaining to yourself why they behave that way.",a:"Dr. Ramani"},
{fi:"Rajasi eivät ole heidän ongelmansa.",en:"Your limits are not their problem.",a:"Narcissus"},
{fi:"Yhteisöllinen narsisti saa ihailua hyvyydellään.",en:"The communal narcissist earns admiration through goodness.",a:"Craig Malkin"},
{fi:"Varoitusmerkki jota et halua nähdä on suurin varoitusmerkki.",en:"The warning sign you don't want to see is the biggest warning sign.",a:"Narcissus"},
{fi:"Narsistiset vanhemmat käyttävät lapsiaan tarpeidensa välineinä.",en:"Narcissistic parents use their children as instruments for their needs.",a:"Alice Miller"},
{fi:"Hyvä elämä alkaa rajoista.",en:"The good life begins with boundaries.",a:"Aristoteles"},
{fi:"Joku joka rakastaa sinua ei tee sinusta epävarman.",en:"Someone who loves you doesn't make you insecure.",a:"Narcissus"},
{fi:"Narsistinen kohteliaisuus on ase.",en:"Narcissistic charm is a weapon.",a:"Sam Vaknin"},
{fi:"Haluatko olla oikeassa vai onnellinen?",en:"Do you want to be right or happy?",a:"Psykologian viisaus"},
{fi:"Pelko on kelvoton ohjenuora elämässä.",en:"Fear is a poor guide for life.",a:"Seneca"},
{fi:"Heikkous ja haavoittuvuus ovat eri asioita.",en:"Weakness and vulnerability are different things.",a:"Brené Brown"},
{fi:"Todellisuuden kieltäminen ei muuta todellisuutta.",en:"Denying reality doesn't change reality.",a:"Marcus Aurelius"},
{fi:"Itseäsi kuunteleminen on radikaalinen teko.",en:"Listening to yourself is a radical act.",a:"Narcissus"},
{fi:"Joskus lähteminen on ainut terveellinen vaihtoehto.",en:"Sometimes leaving is the only healthy option.",a:"Dr. Ramani"},
{fi:"Manipuloija luo tilanteen, johon vain he tietävät säännöt.",en:"The manipulator creates a situation where only they know the rules.",a:"Lundy Bancroft"},
{fi:"Tunne-elämän tyrannus kätkeytyy charmin taakse.",en:"Emotional tyranny hides behind charm.",a:"Shahida Arabi"},
{fi:"Trauma ei ole heikkous – se on selviytymisen tulos.",en:"Trauma is not weakness – it is the result of survival.",a:"Pete Walker"},
{fi:"Tietoisuus vaatii rohkeutta katsoa.",en:"Awareness requires the courage to look.",a:"Narcissus"},
{fi:"Narsistinen käytös on opittu, mutta muutos on mahdollinen – harvoin tapahtuva.",en:"Narcissistic behavior is learned, but change is possible – rarely happening.",a:"Ross Rosenberg"},
{fi:"Sinun vihasi viesti on raja.",en:"The message of your anger is a boundary.",a:"Narcissus"},
{fi:"Ei-sana on sinun oikeutesi.",en:"The word no is your right.",a:"Nedra Glover Tawwab"},
{fi:"Riippuvuus rakkauden naamioituna on kontrollia.",en:"Dependency masked as love is control.",a:"Erich Fromm"},
{fi:"Oman arvon löytyminen on parantumisen sydän.",en:"Finding your own worth is the heart of healing.",a:"Shannon Thomas"},
{fi:"Pysy todellisuudessa vaikka se sattuu.",en:"Stay in reality even when it hurts.",a:"Robin Stern"},
{fi:"Narsistinen persoonallisuus on puolustusmekanismi, ei ydin.",en:"The narcissistic personality is a defense mechanism, not the core.",a:"Heinz Kohut"},
{fi:"Surutyö on välttämätön osa toipumista.",en:"Grief work is an essential part of recovery.",a:"Pete Walker"},
{fi:"Sisäinen lapsi on osa sinua joka kaipaa parantamista.",en:"The inner child is the part of you that needs healing.",a:"Pete Walker"},
{fi:"Narsistinen manipulaatio tapahtuu hitaasti, kuin keittyvä sammakko.",en:"Narcissistic manipulation happens slowly, like a boiling frog.",a:"Narcissus"},
{fi:"Identiteetti ei ole muuttumaton – se kasvaa.",en:"Identity is not fixed – it grows.",a:"Kierkegaard"},
{fi:"Itsekseen eksyminen on osa toipumista.",en:"Getting lost within oneself is part of recovery.",a:"Narcissus"},
{fi:"Sinussa on voimaa jonka et vielä tiedä.",en:"There is strength in you that you don't yet know.",a:"Rumi"},
{fi:"Narsistinen suhde vaikuttaa aivoihin, ei vain sydämeen.",en:"A narcissistic relationship affects the brain, not just the heart.",a:"Shahida Arabi"},
{fi:"Rajas ovat sinun – ei kenenkään muun.",en:"Your limits are yours – not anyone else's.",a:"Nedra Glover Tawwab"},
{fi:"Manipulaattorin uhri ei ole tyhmä – hän on inhimillinen.",en:"The manipulator's victim isn't stupid – they're human.",a:"Dr. Ramani"},
{fi:"Jokainen paranemisaskel on rohkea.",en:"Every step toward healing is courageous.",a:"Narcissus"},
{fi:"Terve itsetunto ei tarvitse ulkopuolista vahvistusta jatkuvasti.",en:"Healthy self-esteem doesn't need constant external validation.",a:"Heinz Kohut"},
{fi:"Narsistinen häpeä on ydinhaava, jota peitetään päivittäin.",en:"Narcissistic shame is a core wound covered up daily.",a:"Brené Brown"},
{fi:"Empatia on lihas jota voidaan vahvistaa.",en:"Empathy is a muscle that can be strengthened.",a:"Craig Malkin"},
{fi:"Kohteliaisuus, joka vaatii kiitosta, on ehdollista.",en:"Kindness that demands gratitude is conditional.",a:"Narcissus"},
{fi:"Sinun ei tarvitse selittää paranemistasi.",en:"You don't have to explain your healing.",a:"Narcissus"},
{fi:"Kaikki suhteet eivät ole korjattavissa.",en:"Not all relationships can be repaired.",a:"Dr. Ramani"},
{fi:"Narsistinen suuttumus on häpeän muoto.",en:"Narcissistic anger is a form of shame.",a:"Sam Vaknin"},
{fi:"Uhriutuminen on narsistinen puolustuskeino.",en:"Victimhood is a narcissistic defense mechanism.",a:"Craig Malkin"},
{fi:"Oikeudenmukaisuus tarkoittaa myös oikeudenmukaisuutta itseäsi kohtaan.",en:"Justice also means justice toward yourself.",a:"Narcissus"},
{fi:"Rakastaminen ei tarkoita oman itsensä kadottamista.",en:"Loving someone doesn't mean losing yourself.",a:"Erich Fromm"},
{fi:"Kognitiivinen empatia ei korvaa tunne-empatiaa.",en:"Cognitive empathy doesn't replace emotional empathy.",a:"Craig Malkin"},
{fi:"Oma kehosi tietää ennen kuin mielesi myöntää.",en:"Your body knows before your mind admits.",a:"Pete Walker"},
{fi:"Joka luo kaaoksen voi kontrolloida sinua sen kautta.",en:"Whoever creates chaos can control you through it.",a:"Narcissus"},
{fi:"Seuraukset ovat rajasi tukijalka.",en:"Consequences are the backbone of your boundaries.",a:"Nedra Glover Tawwab"},
{fi:"Narsistinen vaimo tai aviomies opettaa sinut pienentymään.",en:"A narcissistic spouse teaches you to shrink.",a:"Dr. Ramani"},
{fi:"Parantuminen on luvan antamista itsellesi kasvaa.",en:"Healing is giving yourself permission to grow.",a:"Narcissus"},
{fi:"Sinua sattuu, koska välität. Välittäminen on arvokas asia.",en:"It hurts because you care. Caring is a valuable thing.",a:"Narcissus"},
{fi:"Narsistinen kollega tekee sinut näkymättömäksi.",en:"A narcissistic colleague makes you invisible.",a:"Narcissus"},
{fi:"Tunnistaminen on voimaannuttavaa.",en:"Recognition is empowering.",a:"Shahida Arabi"},
{fi:"Syvä sisäinen tyhjyys ei täyty ulkopuolisella ihailulla.",en:"Deep inner emptiness is not filled by external admiration.",a:"Alexander Lowen"},
{fi:"Kiintyminen manipulaattoriin on biologinen vastaus, ei heikkous.",en:"Attachment to a manipulator is a biological response, not weakness.",a:"Shahida Arabi"},
{fi:"Et voi saada aitoa hoivaa ihmiseltä joka ei rakasta itseään.",en:"You cannot be truly cared for by someone who doesn't love themselves.",a:"Narcissus"},
{fi:"Toipuminen on opiskelua siitä mitä terve suhde tarkoittaa.",en:"Recovery is learning what a healthy relationship means.",a:"Dr. Ramani"},
{fi:"Narsistinen pomo luo ympäristön jossa kukaan ei koe olevansa tarpeeksi.",en:"A narcissistic boss creates an environment where no one feels enough.",a:"Narcissus"},
{fi:"Jokainen päivä jolloin valitset itsesi on voitto.",en:"Every day you choose yourself is a victory.",a:"Narcissus"},
{fi:"Psykopaattinen narsismi on harvinainen mutta äärimmäisen tuhoisa.",en:"Psychopathic narcissism is rare but extremely destructive.",a:"Sam Vaknin"},
{fi:"Sinulla on oikeus omiin muistoihisi.",en:"You have a right to your own memories.",a:"Narcissus"},
{fi:"Pelkääminen hyväksikäytetyksi tulemisesta on normaali traumavaste.",en:"Fearing being exploited again is a normal trauma response.",a:"Pete Walker"},
{fi:"Empaattinen ihminen on usein narsistin kohde.",en:"An empathic person is often a narcissist's target.",a:"Dr. Ramani"},
{fi:"Sinun kärsimyksesi on todellinen, vaikka joku sanoo muuta.",en:"Your suffering is real even if someone says otherwise.",a:"Narcissus"},
{fi:"Narsistinen suhde on asymmetrinen.",en:"A narcissistic relationship is asymmetric.",a:"Sam Vaknin"},
{fi:"Ilman empatiaa ei voi olla aitoa rakkautta.",en:"Without empathy there can be no real love.",a:"Erich Fromm"},
{fi:"Sinun ei tarvitse todistaa arvoasi kenellekään.",en:"You don't need to prove your worth to anyone.",a:"Brené Brown"},
{fi:"Rajat ovat rakkauslausuntoja itsellesi.",en:"Boundaries are love declarations to yourself.",a:"Nedra Glover Tawwab"},
{fi:"Viha loukatusta ihmisestä on tervettä – toiminta määrittää kaiken.",en:"Anger from a hurt person is healthy – action defines everything.",a:"Narcissus"},
{fi:"Narsistinen pettymys on räjähtävä.",en:"Narcissistic disappointment is explosive.",a:"Sam Vaknin"},
{fi:"Toivuttua ei enää voi olla niillä samoilla silmillä.",en:"Once healed, you can't see with the same eyes.",a:"Narcissus"},
{fi:"Luottamus rakentuu tekojen kautta, ei sanojen.",en:"Trust is built through actions, not words.",a:"Psykologian viisaus"},
{fi:"Henkinen kasvu on kivulias mutta välttämätön.",en:"Mental growth is painful but necessary.",a:"Kierkegaard"},
{fi:"Narsistinen suhde opettaa vääriä uskomuksia rakkaudesta.",en:"A narcissistic relationship teaches false beliefs about love.",a:"Shannon Thomas"},
{fi:"Lakkaa yrittämästä saada hyväksyntää niiltä jotka eivät anna sitä.",en:"Stop seeking approval from those who withhold it.",a:"Dr. Ramani"},
{fi:"Olet tarpeeksi. Aina olit.",en:"You are enough. You always were.",a:"Brené Brown"},
{fi:"Anteeksipyyntö ilman muutosta on häirintää.",en:"An apology without change is harassment.",a:"Narcissus"},
{fi:"Lähtiessäsi annat tilaa paremmalle.",en:"When you leave, you make room for something better.",a:"Narcissus"},
{fi:"Häpeän kasvoilla on monia nimiä.",en:"The face of shame has many names.",a:"Brené Brown"},
{fi:"Narsistinen idealisointi murskautuu aina.",en:"Narcissistic idealization always shatters.",a:"Sam Vaknin"},
{fi:"Rakkauden kieli on teot, ei vain sanat.",en:"The language of love is actions, not just words.",a:"Gary Chapman"},
{fi:"Paranemisessa on kyse oman äänen löytämisestä.",en:"Healing is about finding your own voice.",a:"Pete Walker"},
{fi:"Et ole ketjuunsa sidottu.",en:"You are not bound to your chain.",a:"Seneca"},
{fi:"Autonomia on ihmisyyden ydin.",en:"Autonomy is the core of humanity.",a:"Erich Fromm"},
{fi:"Narsistinen rakenne on puolustusjärjestelmä.",en:"The narcissistic structure is a defense system.",a:"Heinz Kohut"},
{fi:"Vahvuus on kyky olla oma itsensä pelottomasti.",en:"Strength is the ability to be yourself fearlessly.",a:"Narcissus"},
{fi:"Onnellisuus ei ole narsistinen tavoite – se on ihmisyys.",en:"Happiness is not a narcissistic goal – it's humanity.",a:"Aristoteles"},
{fi:"Emotionaalinen väkivalta jättää haavoja joita silmä ei näe.",en:"Emotional abuse leaves wounds the eye cannot see.",a:"Shahida Arabi"},
{fi:"Sanomalla ei sinä suojelet sekä itseäsi että toista.",en:"By saying no you protect both yourself and the other.",a:"Narcissus"},
{fi:"Narsistinen suhde alkaa usein parhaimmalta mitä olet kokenut.",en:"A narcissistic relationship often begins as the best you've ever experienced.",a:"Jackson MacKenzie"},
{fi:"Käyttäytyminen kertoo enemmän kuin sanat.",en:"Behavior tells more than words.",a:"Psykologian viisaus"},
{fi:"Aito rakkaus haluaa sinulle vapauden.",en:"True love wants freedom for you.",a:"Erich Fromm"},
{fi:"Trauma-aktivaatio voi tuntua kuin nykyhetki mutta se on menneisyyttä.",en:"Trauma activation can feel like the present but it is the past.",a:"Pete Walker"},
{fi:"Sinulla on lupa ottaa tilaa.",en:"You have permission to take up space.",a:"Nedra Glover Tawwab"},
{fi:"Narsistinen fantasiaan eläminen on pako todellisuudesta.",en:"Living in narcissistic fantasy is an escape from reality.",a:"Sam Vaknin"},
{fi:"Jokainen terve valinta rakentaa parempaa tulevaisuutta.",en:"Every healthy choice builds a better future.",a:"Narcissus"},
{fi:"Lakkaa pienentymästä mahtuaksesi toisen maailmaan.",en:"Stop shrinking to fit into someone else's world.",a:"Narcissus"},
{fi:"Narsistinen rakennelma on pettävä hiekkaan rakennettu talo.",en:"The narcissistic construct is a house built on deceptive sand.",a:"Alexander Lowen"},
{fi:"Elämä on liian lyhyt vaarallisiin suhteisiin.",en:"Life is too short for dangerous relationships.",a:"Seneca"},
{fi:"Itsenäisyys ei ole itsekkyyttä.",en:"Independence is not selfishness.",a:"Narcissus"},
{fi:"Näet parhaiten sieltä mistä olet selvin.",en:"You see clearest from where you are most clear.",a:"Narcissus"},
{fi:"Sinä voit muuttua. He eivät välttämättä voi.",en:"You can change. They may not be able to.",a:"Dr. Ramani"},
{fi:"Rajat ilman seurauksia ovat pyyntöjä.",en:"Boundaries without consequences are requests.",a:"Nedra Glover Tawwab"},
{fi:"Narsismi on itsen ja muiden kapteenin välinen taistelu.",en:"Narcissism is a battle between the captain of self and others.",a:"Ross Rosenberg"},
{fi:"Itseensä tutustuminen on elämän tärkeimmät opinnot.",en:"Getting to know yourself is the most important study of life.",a:"Aristoteles"},
{fi:"Arvokas ihminen ei tarvitse toisten nöyryyttämistä.",en:"A person of value does not need to humiliate others.",a:"Narcissus"},
{fi:"Parantaminen on rohkeutta mennä kohti pelkoa.",en:"Healing is the courage to move toward fear.",a:"Narcissus"},
{fi:"Narsistinen viha on pelkoa.",en:"Narcissistic rage is fear.",a:"Sam Vaknin"},
{fi:"Suhde joka vie enemmän kuin antaa ei ole tasapainoinen.",en:"A relationship that takes more than it gives is not balanced.",a:"Narcissus"},
{fi:"Vanhin ja viisain viisaus: tunne itsesi.",en:"The oldest and wisest wisdom: know yourself.",a:"Aristoteles"},
{fi:"Narsistinen yhteisöllinen käyttää hyväksynnän etsintään hyvyyttä.",en:"The communal narcissist uses goodness to seek approval.",a:"Craig Malkin"},
{fi:"Sinun elämäsi on sinun – ei heidän projektinsa.",en:"Your life is yours – not their project.",a:"Narcissus"},
{fi:"Itsenäinen ajattelu on narsistin pahin uhka.",en:"Independent thinking is the narcissist's worst threat.",a:"Sam Vaknin"},
{fi:"Suhde jossa olet aina väärässä ei ole tervettä.",en:"A relationship where you are always wrong is not healthy.",a:"Narcissus"},
{fi:"Manipuloijan salaisuus on, että he tarvitsevat sinut.",en:"The manipulator's secret is that they need you.",a:"Lundy Bancroft"},
{fi:"Terve suhde kasvaa. Narsistinen kutistuu.",en:"A healthy relationship grows. A narcissistic one shrinks.",a:"Narcissus"},
{fi:"Et tarvitse heidän suostumustaan elääksesi hyvin.",en:"You don't need their permission to live well.",a:"Narcissus"},
{fi:"Narsistinen devalvaatio tulee aina yllätyksenä.",en:"Narcissistic devaluation always comes as a surprise.",a:"Dr. Ramani"},
{fi:"Terveellä rajalla on aina arvo.",en:"A healthy boundary always has worth.",a:"Nedra Glover Tawwab"},
{fi:"Olet päättänyt jo enemmän kuin tiedät.",en:"You have already decided more than you know.",a:"Narcissus"},
{fi:"Luottamus on paras selitys.",en:"Trust is the best explanation.",a:"Kierkegaard"},
{fi:"Toipuminen on oppimista sietämään epävarmuutta.",en:"Recovery is learning to tolerate uncertainty.",a:"Pete Walker"},
{fi:"Joka haluaa sinua – etsii sinua. Muut selittelevät.",en:"Whoever wants you – seeks you. Others make excuses.",a:"Narcissus"},
{fi:"Narsistinen suhde opettaa sinulle kenen todellisuus on tärkeämpi.",en:"A narcissistic relationship teaches you whose reality matters more.",a:"Robin Stern"},
{fi:"Elämä alkaa todellisuudesta.",en:"Life begins with reality.",a:"Narcissus"},
{fi:"Sinun arvokkuutesi on syntymässä annettu – ei ansaittava.",en:"Your worth was given at birth – not something to be earned.",a:"Brené Brown"},
{fi:"Empatia ei tarkoita rajojen puuttumista.",en:"Empathy does not mean the absence of boundaries.",a:"Narcissus"},
{fi:"Narsistinen kontrolloiniti on pelkoa menettämisestä.",en:"Narcissistic control is fear of losing.",a:"Sam Vaknin"},
{fi:"Aitous on rohkeutta olla haavoittuvainen.",en:"Authenticity is the courage to be vulnerable.",a:"Brené Brown"},
{fi:"Oman mielen rauhassa ei tarvita hyväksyntää.",en:"The peace of your own mind needs no approval.",a:"Marcus Aurelius"},
{fi:"Jokainen taistelu jonka olet käynyt on tehnyt sinusta vahvemman.",en:"Every battle you've fought has made you stronger.",a:"Narcissus"},
{fi:"Narsistinen suhde on harjoituskenttä rajojen asettamiselle.",en:"A narcissistic relationship is a training ground for setting limits.",a:"Narcissus"},
{fi:"Tieto ja tietoisuus ovat eri asioita.",en:"Knowledge and awareness are different things.",a:"Narcissus"},
{fi:"Sinä olet kokonainen ilman heitä.",en:"You are whole without them.",a:"Narcissus"},
{fi:"Rakkauden vastainen on välinpitämättömyys, ei viha.",en:"The opposite of love is indifference, not hate.",a:"Elie Wiesel"},
{fi:"Narsistinen suhde käyttää optimismiasi sinua vastaan.",en:"A narcissistic relationship uses your optimism against you.",a:"Shahida Arabi"},
{fi:"Omat virheesi ovat opettajasi – ei häpeäsi.",en:"Your mistakes are your teachers – not your shame.",a:"Narcissus"},
{fi:"Toipuminen on matka, ei päämäärä.",en:"Recovery is a journey, not a destination.",a:"Narcissus"},
{fi:"Narsistinen suuttumus on naamio avuttomuudelle.",en:"Narcissistic anger is a mask for helplessness.",a:"Heinz Kohut"},
{fi:"Joskus rakkauden akti on antaa mennä.",en:"Sometimes the act of love is to let go.",a:"Narcissus"},
{fi:"Käytös joka sattuu on opetus – ei rangaistus.",en:"Behavior that hurts is a lesson – not a punishment.",a:"Narcissus"},
{fi:"Narsistinen fantasiamaailma on suljettu järjestelmä.",en:"The narcissistic fantasy world is a closed system.",a:"Sam Vaknin"},
{fi:"Et ole liikaa kenellekään joka sopii sinulle.",en:"You are not too much for someone who fits you.",a:"Narcissus"},
{fi:"Tietoisuus omista reaktioistasi on viisauden alku.",en:"Awareness of your own reactions is the beginning of wisdom.",a:"Marcus Aurelius"},
{fi:"Narsistinen hooverointi on naamioitua manipulaatiota.",en:"Narcissistic hoovering is disguised manipulation.",a:"Jackson MacKenzie"},
{fi:"Jokainen haaste on mahdollisuus kasvaa.",en:"Every challenge is an opportunity to grow.",a:"Narcissus"},
{fi:"Oma arvosi ei muutu sen mukaan miten joku kohtelee sinua.",en:"Your value doesn't change according to how someone treats you.",a:"Brené Brown"},
{fi:"Tunne-elämän taidot ovat opeteltavissa.",en:"Emotional skills can be learned.",a:"Psykologian viisaus"},
{fi:"Narsistinen rakenne on suojakuori tuhoutuneen ytimen ympärillä.",en:"The narcissistic structure is a shell protecting a destroyed core.",a:"Alexander Lowen"},
{fi:"Toipuminen tarkoittaa, ettei enää tarvitse selittää omaa kipuaan.",en:"Recovery means no longer having to explain your pain.",a:"Narcissus"},
{fi:"Terveys ei tarkoita kaiken olevan hyvin – se tarkoittaa osaat käsitellä.",en:"Health doesn't mean everything is fine – it means you can handle it.",a:"Narcissus"},
{fi:"Turvallisuus on tunne jota oikeassa suhteessa ei tarvitse ansaita.",en:"Safety is a feeling you don't have to earn in a right relationship.",a:"Narcissus"},
{fi:"Narsistinen askel taaksepäin on parempi kuin kaatuminen.",en:"A narcissistic step backwards is better than falling.",a:"Narcissus"},
{fi:"Oman totuutesi kertominen on vapautuminen.",en:"Telling your own truth is liberation.",a:"Narcissus"},
{fi:"Kipuasi ei tarvitse selitellä.",en:"You don't have to justify your pain.",a:"Shannon Thomas"},
{fi:"Narsistinen suhde muuttaa sinun näkökulman itsestäsi.",en:"A narcissistic relationship changes your perspective of yourself.",a:"Robin Stern"},
{fi:"Sinulla on oikeus olla sellaisessa suhteessa jossa et pelkää.",en:"You have the right to be in a relationship where you aren't afraid.",a:"Narcissus"},
{fi:"Mikä kasvaa varjossa, kasvaa hitaasti – mutta kasvaa.",en:"What grows in shadow, grows slowly – but grows.",a:"Narcissus"},
{fi:"Narsistisen suhteen jälkeinen viisaus on elämän kallein opetus.",en:"The wisdom after a narcissistic relationship is life's most expensive lesson.",a:"Narcissus"},
{fi:"Empatia ei ole sinun heikkoutesi – se on sinun vahvuutesi.",en:"Empathy is not your weakness – it is your strength.",a:"Dr. Ramani"},
{fi:"Tule omaksi etusijaksesi.",en:"Become your own priority.",a:"Narcissus"},
{fi:"Rakkauden puute lapsuudessa jättää jäljen, mutta ei kohtaloasi.",en:"The lack of love in childhood leaves a mark but not your fate.",a:"Alice Miller"},
{fi:"Paras asia mitä voit tehdä itsellesi on kasvaa.",en:"The best thing you can do for yourself is grow.",a:"Narcissus"},
{fi:"Haavasi eivät ole häpeäsi.",en:"Your wounds are not your shame.",a:"Brené Brown"},
{fi:"Narsistinen fantasiassa eläminen on pako vastuusta.",en:"Living in narcissistic fantasy is an escape from responsibility.",a:"Sam Vaknin"},
{fi:"Yhteiskunta ihannoii narsistisia piirteitä, joista se kärsii.",en:"Society idealizes narcissistic traits from which it suffers.",a:"Narcissus"},
{fi:"Jokainen parantaminen on pieni vallankumous.",en:"Every healing is a small revolution.",a:"Narcissus"},
{fi:"Narsistinen suuntautuminen on haavottunut suuntautuminen.",en:"Narcissistic orientation is a wounded orientation.",a:"Erich Fromm"},
{fi:"Oman kivun tunnistaminen on rohkeutta.",en:"Recognizing your own pain is courage.",a:"Narcissus"},
{fi:"Rajasi ovat pyhät.",en:"Your limits are sacred.",a:"Nedra Glover Tawwab"},
{fi:"Väkivalta on valinta, ei kohtalo.",en:"Violence is a choice, not a fate.",a:"Lundy Bancroft"},
{fi:"Toipumisen jälkeen näet sen mitä ennen et voinut.",en:"After recovery you see what you couldn't before.",a:"Narcissus"},
{fi:"Narsistinen kiitollisuus on aina ehdollista.",en:"Narcissistic gratitude is always conditional.",a:"Sam Vaknin"},
{fi:"Sinulla on oikeus luottaa omiin kokemuksiisi.",en:"You have the right to trust your own experiences.",a:"Narcissus"},
{fi:"Aito suhde kestää rehellisyyden.",en:"A genuine relationship endures honesty.",a:"Narcissus"},
{fi:"Narsistinen hylkäys on narsistin tapa hallita.",en:"Narcissistic discard is the narcissist's way of controlling.",a:"Dr. Ramani"},
{fi:"Sinuun tallennettu kaaos ei ole sinun.",en:"The chaos stored in you is not yours.",a:"Narcissus"},
{fi:"Kehosi on kotonasi.",en:"Your body is your home.",a:"Narcissus"},
{fi:"Kun joudut ansaitsemaan rakkauden, se ei ole rakkautta.",en:"When you have to earn love, it is not love.",a:"Narcissus"},
{fi:"Narsistinen manipulaatio vaikuttaa aivojen palkitsemisjärjestelmään.",en:"Narcissistic manipulation affects the brain's reward system.",a:"Shahida Arabi"},
{fi:"Ainoa tapa on läpi.",en:"The only way is through.",a:"Narcissus"},
{fi:"Empatiasi arvo ei riipu siitä saatko sitä takaisin.",en:"The value of your empathy doesn't depend on whether you get it back.",a:"Narcissus"},
{fi:"Parantua tarkoittaa oppia elämään ilman heidän todellisuuttaan.",en:"To heal means to learn to live without their reality.",a:"Robin Stern"},
{fi:"Narsistinen vilkkaus on pelko.",en:"Narcissistic volatility is fear.",a:"Sam Vaknin"},
{fi:"Et tarvitse heidän selityksiään ymmärtääksesi mitä tapahtui.",en:"You don't need their explanations to understand what happened.",a:"Narcissus"},
{fi:"Omasta itsestä piittaaminen on ensi askel.",en:"Caring for yourself is the first step.",a:"Narcissus"},
{fi:"Narsistinen suhde vie tärkeimmän: käsityksesi itsestäsi.",en:"A narcissistic relationship robs you of the most important: your sense of self.",a:"Dr. Ramani"},
{fi:"Et ole rikkinäinen – olet parantumassa.",en:"You are not broken – you are healing.",a:"Narcissus"},
{fi:"Etsitään rakkautta vääriltä ihmisiltä liian usein.",en:"We seek love from the wrong people too often.",a:"Narcissus"},
{fi:"Narsistisen suhteen loppu on surun, ei häpeän aika.",en:"The end of a narcissistic relationship is a time for grief, not shame.",a:"Narcissus"},
{fi:"Sinun historiasi ei ole sinun tulevaisuutesi.",en:"Your history is not your future.",a:"Narcissus"},
{fi:"Narsistinen kaaos on heidän hallintakeino.",en:"Narcissistic chaos is their control tool.",a:"Dr. Ramani"},
{fi:"Oikea rakkautta eivät tarvitse jatkuvaa todistamista.",en:"Real love does not need constant proving.",a:"Narcissus"},
{fi:"Itseensä luottaminen on suurin teko.",en:"Trusting yourself is the greatest act.",a:"Narcissus"},
{fi:"Kipu joka on nimetty on helpompi kantaa.",en:"Pain that is named is easier to carry.",a:"Brené Brown"},
{fi:"Narsistinen elämä on kuin tyhjä näyttämö täynnä rekvisiittaa.",en:"A narcissistic life is like an empty stage full of props.",a:"Sam Vaknin"},
{fi:"Arvokkuus löytyy siitä mistä et etsi.",en:"Dignity is found where you're not looking.",a:"Narcissus"},
{fi:"Paraneminen tarkoittaa: sinä tulet ensin.",en:"Healing means: you come first.",a:"Narcissus"},
{fi:"Narsistinen suuttumus etsii kohdettaan.",en:"Narcissistic rage seeks its target.",a:"Sam Vaknin"},
{fi:"Tulevaisuutesi ei ole mennyt – se odottaa.",en:"Your future has not gone – it waits.",a:"Narcissus"},
{fi:"Tunteiden purkaminen on terveyttä.",en:"Releasing emotions is health.",a:"Narcissus"},
{fi:"Narsistinen suhde vie unesi, tunteesi ja identiteettisi.",en:"A narcissistic relationship takes your sleep, feelings, and identity.",a:"Shahida Arabi"},
{fi:"Rakastat parhaiten kun olet kokonainen.",en:"You love best when you are whole.",a:"Narcissus"},
{fi:"Manipulaattori ei tarvitse totuutta – he tarvitsevat tarinan.",en:"The manipulator doesn't need truth – they need the story.",a:"Lundy Bancroft"},
{fi:"Tervehtyminen alkaa rehellisyydestä itselle.",en:"Getting well begins with honesty to yourself.",a:"Narcissus"},
{fi:"Sinulla on oikeus olla oma mielipiteesi.",en:"You have the right to your own opinion.",a:"Narcissus"},
{fi:"Narsistinen rakenne pitää sinut loukkussa fantasiassa.",en:"The narcissistic construct keeps you trapped in a fantasy.",a:"Sam Vaknin"},
{fi:"Jokainen selviytyjä on sankari omassa tarinassaan.",en:"Every survivor is a hero in their own story.",a:"Narcissus"},
{fi:"Rajojen asettaminen on itsesi rakastamista.",en:"Setting limits is loving yourself.",a:"Nedra Glover Tawwab"},
{fi:"Narsistinen häirintä jatkuu myös eron jälkeen.",en:"Narcissistic harassment continues after separation too.",a:"Dr. Ramani"},
{fi:"Joka päivä olet vahvempi kuin eilen.",en:"Every day you are stronger than yesterday.",a:"Narcissus"},
{fi:"Lasten tarpeet eivät vanhene.",en:"Children's needs don't expire.",a:"Alice Miller"},
{fi:"Narsistinen kontrolloiniti naamioituu huolenpidoksi.",en:"Narcissistic control disguises itself as care.",a:"Narcissus"},
{fi:"Sinulla on oikeus elämään jossa tunnet olosi turvalliseksi.",en:"You have the right to a life where you feel safe.",a:"Narcissus"},
{fi:"Vaikka et uskoisi sitä – olet tarpeeksi arvokas.",en:"Even if you don't believe it – you are worthy enough.",a:"Narcissus"},
{fi:"Narsistinen häpeäkierre on noidankehä.",en:"The narcissistic shame spiral is a vicious cycle.",a:"Sam Vaknin"},
{fi:"Anteeksiantaminen ei tarkoita yhteydenpidon jatkamista.",en:"Forgiveness doesn't mean continuing contact.",a:"Narcissus"},
{fi:"Aina ei tarvita ymmärrystä – joskus riittää turvallisuus.",en:"Understanding isn't always needed – sometimes safety is enough.",a:"Narcissus"},
{fi:"Narsistinen suhde jättää sinut epäilemään omaa arvoasi.",en:"A narcissistic relationship leaves you doubting your own value.",a:"Dr. Ramani"},
{fi:"Elämä alkaa kun pysähdyt yrittämästä miellyttää kaikkia.",en:"Life begins when you stop trying to please everyone.",a:"Narcissus"},
{fi:"Narsistinen toinen puoli etsii korvausuhria.",en:"The narcissistic partner seeks a replacement victim.",a:"Sam Vaknin"},
{fi:"Et ole olemassa heitä varten.",en:"You do not exist for them.",a:"Narcissus"},
{fi:"Rohkeus ei tarkoita pelottomuutta – se tarkoittaa toimintaa pelosta huolimatta.",en:"Courage doesn't mean fearlessness – it means acting despite fear.",a:"Narcissus"},
{fi:"Narsistinen kohde on aina väärässä – koska narsisti päättää.",en:"The narcissist's target is always wrong – because the narcissist decides.",a:"Sam Vaknin"},
{fi:"Sinulle tehty kipu on totta, vaikka kukaan muu ei uskoisi.",en:"The pain done to you is real, even if no one else believes it.",a:"Narcissus"},
{fi:"Omaan elämään investoiminen on paras valinta.",en:"Investing in your own life is the best choice.",a:"Narcissus"},
{fi:"Narsistinen suhde häiritsee kiintymysjärjestelmäsi.",en:"A narcissistic relationship disrupts your attachment system.",a:"Shahida Arabi"},
{fi:"Sinun ei tarvitse kärsiä hiljaa.",en:"You don't have to suffer in silence.",a:"Dr. Ramani"},
{fi:"Terve tulevaisuus rakentuu rehellisyydelle.",en:"A healthy future is built on honesty.",a:"Narcissus"},
{fi:"Narsistinen suhde voi tuntua lohtuisalta koska se on tuttua.",en:"A narcissistic relationship can feel comforting because it's familiar.",a:"Pete Walker"},
{fi:"Omat tarpeet eivät ole ylellisyys.",en:"Your own needs are not a luxury.",a:"Narcissus"},
{fi:"Toipuminen vaatii aikaa – anna se itsellesi.",en:"Recovery takes time – give it to yourself.",a:"Narcissus"},
{fi:"Narsistinen suhde muuttaa sinun käsityksesi normaalista.",en:"A narcissistic relationship changes your perception of normal.",a:"Dr. Ramani"},
{fi:"Lähteminen ei ole epäonnistuminen.",en:"Leaving is not failure.",a:"Narcissus"},
{fi:"Narsistinen toimintatapa ei johdu sinusta.",en:"Narcissistic behavior patterns don't stem from you.",a:"Narcissus"},
{fi:"Rajojen ylittäjä kertoo paljon itsestään.",en:"One who crosses boundaries tells a lot about themselves.",a:"Nedra Glover Tawwab"},
{fi:"Itsensä tuntemus on viisauden alku.",en:"Self-knowledge is the beginning of wisdom.",a:"Aristoteles"},
{fi:"Sinulle on lupa surra mitä menetit.",en:"You are allowed to grieve what you lost.",a:"Pete Walker"},
{fi:"Narsistinen rakkaus tuhoutuu kun tarvitaan todellista läheisyyttä.",en:"Narcissistic love disintegrates when real intimacy is needed.",a:"Alexander Lowen"},
{fi:"Oma arvokkuutesi kasvaa, kun asetat rajoja.",en:"Your own dignity grows when you set limits.",a:"Narcissus"},
{fi:"Jokainen pieni askel eteenpäin lasketaan.",en:"Every small step forward counts.",a:"Narcissus"},
{fi:"Hyvä suoja on tietoisuus.",en:"Good protection is awareness.",a:"Narcissus"},
{fi:"Narsistinen kontakti jälkeen eron ei auta toipumista.",en:"Narcissistic contact after separation does not help recovery.",a:"Jackson MacKenzie"},
{fi:"Sinä olet arvokas ilman kenenkään todistamista.",en:"You are valuable without anyone's proof.",a:"Narcissus"},
{fi:"Toipuminen alkaa sanomalla ensi kerran totuuden.",en:"Recovery begins when you first tell the truth.",a:"Narcissus"},
{fi:"Narsistinen rakenne on kuin peili joka heijastaa väärin.",en:"The narcissistic construct is like a mirror that reflects incorrectly.",a:"Sam Vaknin"},
{fi:"Joka taisteli on rohkea.",en:"Whoever fought is courageous.",a:"Narcissus"},
{fi:"Elämä alkaa juuri nyt.",en:"Life begins right now.",a:"Narcissus"},
{fi:"Sinulle kuuluu enemmän kuin mitä olet saanut.",en:"You deserve more than what you've received.",a:"Narcissus"},
{fi:"Narsismin ymmärtäminen ei tarkoita sen hyväksymistä.",en:"Understanding narcissism doesn't mean accepting it.",a:"Dr. Ramani"},
{fi:"Turvallisuus on ihmisoikeus.",en:"Safety is a human right.",a:"Narcissus"},
{fi:"Narsistinen suhde ei opeta rakkautta – se opettaa selviytymistä.",en:"A narcissistic relationship doesn't teach love – it teaches survival.",a:"Narcissus"},
{fi:"Sinussa on voima kääntää tämä kokemus viisaudeksi.",en:"Within you is the power to turn this experience into wisdom.",a:"Narcissus"},
{fi:"Narsistinen suhde varastaa ajan mutta ei tulevaisuuttasi.",en:"A narcissistic relationship steals time but not your future.",a:"Narcissus"},
{fi:"Tunne-elämän väkivalta on todellinen, vaikka jättää näkymättömiä merkkejä.",en:"Emotional abuse is real even when it leaves invisible marks.",a:"Shahida Arabi"},
{fi:"Itseensä tutustuminen on elämän tärkein projekti.",en:"Getting to know yourself is life's most important project.",a:"Narcissus"},
{fi:"Narsistinen suhde tekee sinusta varoittavan esimerkin toisille.",en:"A narcissistic relationship makes you a warning example for others.",a:"Narcissus"},
{fi:"Kukaan ei ole oikeutettu kontrolloimaan sinua.",en:"No one is entitled to control you.",a:"Lundy Bancroft"},
{fi:"Terve ihminen ilmaisee tarpeitaan – ei manipuloi niillä.",en:"A healthy person expresses their needs – doesn't manipulate with them.",a:"Narcissus"},
{fi:"Kipu on opettaja, ei rangaistus.",en:"Pain is a teacher, not a punishment.",a:"Narcissus"},
{fi:"Jotta voit rakastaa muita, on rakastettava itseään ensin.",en:"To love others, one must love oneself first.",a:"Erich Fromm"},
{fi:"Narsistinen esitys vaihtelee – yleisö ratkaisee.",en:"Narcissistic performance varies – it depends on the audience.",a:"Sam Vaknin"},
{fi:"Salaisuutesi kuuluvat sinulle.",en:"Your secrets belong to you.",a:"Narcissus"},
{fi:"Itsensä parantaminen on kaikkein rohkein teko.",en:"Healing yourself is the most courageous act.",a:"Narcissus"},
{fi:"Manipuloija käyttää sinun vahvuuksiasi sinua vastaan.",en:"The manipulator uses your strengths against you.",a:"Shahida Arabi"},
{fi:"Narsistinen rakastuminen on yhdestä ihmisestä rakastavana.",en:"Narcissistic falling in love is one person loving themselves through another.",a:"Alexander Lowen"},
{fi:"Itsesi hyväksyminen on matkan ensimmäinen askel.",en:"Accepting yourself is the first step of the journey.",a:"Narcissus"},
{fi:"Terve suhde ei pelota.",en:"A healthy relationship doesn't frighten.",a:"Narcissus"},
{fi:"Miellyttämisen pakko on opittu selviytymisstrategia.",en:"The compulsion to please is a learned survival strategy.",a:"Pete Walker"},
{fi:"Narsistinen suhde opettaa: pidä se itsestäsi suojassa.",en:"A narcissistic relationship teaches: protect yourself.",a:"Narcissus"},
{fi:"Parannus alkaa kipua katsomalla.",en:"Healing begins by looking at the pain.",a:"Narcissus"},
{fi:"Et ansaitse tulla hylätyksi hiljaisuudella.",en:"You don't deserve to be abandoned with silence.",a:"Narcissus"},
{fi:"Ihmissuhdetaidot ovat harjoittelua vaativia taitoja.",en:"Relationship skills are skills that require practice.",a:"Psykologian viisaus"},
{fi:"Narsistinen kiukku ei johdu sinusta – se on heissä.",en:"Narcissistic fury doesn't stem from you – it is in them.",a:"Dr. Ramani"},
{fi:"Sinulle on lupa olla paha.",en:"You are allowed to be angry.",a:"Narcissus"},
{fi:"Empatia on ovi toisen todellisuuteen.",en:"Empathy is a door into another's reality.",a:"Heinz Kohut"},
{fi:"Narsistinen fantasia ei kestä kosketusta todellisuuteen.",en:"Narcissistic fantasy can't withstand contact with reality.",a:"Sam Vaknin"},
{fi:"Parantuminen alkaa sieltä missä olet.",en:"Healing begins where you are.",a:"Narcissus"},
{fi:"Sinulla on oikeus muuttaa mieltäsi.",en:"You have the right to change your mind.",a:"Narcissus"},
{fi:"Oman elämän rakentaminen on itsensä rakastamista.",en:"Building your own life is self-love.",a:"Narcissus"},
{fi:"Narsistinen suuttumus on lapsen raivo aikuisen kehossa.",en:"Narcissistic rage is a child's tantrum in an adult's body.",a:"Heinz Kohut"},
{fi:"Toivottavuutesi ei riipu siitä mitä olet joutunut kestämään.",en:"Your desirability doesn't depend on what you've had to endure.",a:"Narcissus"},
{fi:"Itsensä tunteminen on vapauden alku.",en:"Knowing yourself is the beginning of freedom.",a:"Narcissus"},
{fi:"Narsistinen suhde vie ajan jonka olisit voinut käyttää kasvamiseen.",en:"A narcissistic relationship takes time you could have spent growing.",a:"Narcissus"},
{fi:"Sinä ansaitset suhteen jossa sinua kuullaan.",en:"You deserve a relationship where you are heard.",a:"Narcissus"},
{fi:"Toipuminen rakentaa sinut vahvemmaksi kuin olit.",en:"Recovery builds you stronger than you were.",a:"Narcissus"},
{fi:"Narsistinen suhde vie energian jonka tarvitset itsellesi.",en:"A narcissistic relationship takes the energy you need for yourself.",a:"Narcissus"},
{fi:"Terve rakkaus on vapaus, ei omistus.",en:"Healthy love is freedom, not ownership.",a:"Erich Fromm"},
{fi:"Hyväksyntä ei tule ulkoa – se rakennetaan sisältä.",en:"Acceptance doesn't come from outside – it is built within.",a:"Narcissus"},
{fi:"Narsistinen menneisyys ei määrää sinun tulevaisuuttasi.",en:"A narcissistic past does not determine your future.",a:"Narcissus"},
{fi:"Jokainen päivä on uusi tilaisuus valita paremmin.",en:"Every day is a new opportunity to choose better.",a:"Narcissus"},
{fi:"Sinulla on oikeus tietää mitä tapahtui.",en:"You have the right to know what happened.",a:"Narcissus"},
{fi:"Narsistinen suhde on opettanut sinulle mitä et enää salli.",en:"A narcissistic relationship has taught you what you will no longer allow.",a:"Dr. Ramani"},
{fi:"Rauhasi on arvokkain omistuksesi.",en:"Your peace is your most precious possession.",a:"Seneca"},
{fi:"Narsistinen rakennelma hajoaa ilman sinun osallistumistasi.",en:"The narcissistic construct collapses without your participation.",a:"Sam Vaknin"},
{fi:"Sinulle on lupa rakastaa itseäsi nyt.",en:"You are allowed to love yourself now.",a:"Narcissus"},
{fi:"Rehellisyys itselle on vapaus.",en:"Honesty with yourself is freedom.",a:"Narcissus"},
{fi:"Narsistinen ihminen tarvitsee sinut peilinsä, ei kumppanikseen.",en:"The narcissistic person needs you as their mirror, not their partner.",a:"Sam Vaknin"},
{fi:"Sinulla on tulevaisuus jonka arvoinen olet.",en:"You have a future worthy of you.",a:"Narcissus"},
{fi:"Väkivallan nimeäminen on askel pois siitä.",en:"Naming abuse is a step away from it.",a:"Lundy Bancroft"},
{fi:"Oma elämäsi on tärkeämpi kuin heidän hyväksyntänsä.",en:"Your own life is more important than their approval.",a:"Narcissus"},
{fi:"Narsistinen suhde loppuu kun lopetat pelin.",en:"A narcissistic relationship ends when you stop playing.",a:"Narcissus"},
{fi:"Kipusi on kutsu paranemiseen.",en:"Your pain is an invitation to heal.",a:"Narcissus"},
{fi:"Sinulla on oikeus nauruun ja iloon.",en:"You have a right to laughter and joy.",a:"Narcissus"},
{fi:"Narsistinen käyttäytyminen opitaan, mutta se voidaan myös oppia pois.",en:"Narcissistic behavior is learned, but can also be unlearned.",a:"Ross Rosenberg"},
{fi:"Tasapaino löytyy siitä kun antaa itselleen saman myötätunnon kuin muille.",en:"Balance is found when you give yourself the same compassion as others.",a:"Kristin Neff"},
{fi:"Toipuminen ei tarkoita unohtamista – se tarkoittaa integroimista.",en:"Recovery doesn't mean forgetting – it means integrating.",a:"Pete Walker"},
{fi:"Sinun totuutesi on pätevä.",en:"Your truth is valid.",a:"Narcissus"},
{fi:"Narsistinen kontakti vähentää oman itsearvostuksesi.",en:"Narcissistic contact reduces your own self-worth.",a:"Dr. Ramani"},
{fi:"Koskaan ei ole liian myöhäistä aloittaa parantumista.",en:"It is never too late to start healing.",a:"Narcissus"},
{fi:"Elät parhaiten silloin kun et pelkää omaa ääntäsi.",en:"You live best when you're not afraid of your own voice.",a:"Narcissus"},
{fi:"Narsistinen suhde vahvistaa tulevaisuuden rajojen tärkeyttä.",en:"A narcissistic relationship reinforces the importance of future boundaries.",a:"Narcissus"},
{fi:"Voitko antaa itsellesi saman rakkauden jonka annoit heille?",en:"Can you give yourself the same love you gave them?",a:"Narcissus"},
{fi:"Arvokkuutesi ei riipu siitä keneltä sait hyväksyntää.",en:"Your dignity doesn't depend on from whom you got approval.",a:"Narcissus"},
{fi:"Narsistinen yhteys on epätasapainoinen jo alusta alkaen.",en:"A narcissistic connection is unbalanced from the very start.",a:"Sam Vaknin"},
{fi:"Omaa tarinaa ei tarvitse kenenkään hyväksyä.",en:"Your own story doesn't need anyone's approval.",a:"Narcissus"},
];
